- turbo.json
This can possibly fix problem with turbo-ignore blocking production promotion
> Add `NEXT_PUBLIC_VERCEL_ENV` env variable to invalidate turbo-ignore

- apps/data-importer/src/modules/customers/customers-importer-nuvo/customers-importer-view.tsx
- apps/data-importer/src/pages/importer.tsx
1. Updated the dropdown columns style
2. Removed margins to increase component's width
> fix: match column styling

- apps/data-importer/src/modules/customers/customers-importer-nuvo/customers-importer-view.tsx
- apps/data-importer/src/pages/importer.tsx
> fix: dark mode

- .changeset/kind-sheep-jog.md
- .changeset/seven-frogs-return.md
- apps/slack/src/lib/slack.ts
- apps/slack/src/pages/api/webhooks/order-created.ts
Fixes `undefined` in slack messages in case of missing customer data
> Slack: Fallback missing user name and last name in message

- apps/emails-and-messages/src/modules/mjml/configuration/get-mjml-configuration.service.ts
- apps/emails-and-messages/src/modules/mjml/configuration/mjml-config-container.ts
- apps/emails-and-messages/src/modules/mjml/configuration/mjml-config-input-schema.ts
- apps/emails-and-messages/src/modules/mjml/configuration/mjml-configuration.router.ts
- apps/emails-and-messages/src/modules/mjml/configuration/ui/mjml-configuration-form.tsx
- apps/emails-and-messages/src/modules/mjml/configuration/ui/mjml-configuration-tab.tsx
Errors were caused by calling the same redirection and data refresh. Since router is faster, it was improperly displaying error message
Fixes: #233 #234
> Fix the blinking of the forms and wrong redirection after removing the conf

- apps/cms/package.json
- apps/cms/src/setup-tests.ts
- apps/cms/vitest.config.ts
- pnpm-lock.yaml
Tests with JSX were failing in CMS app, this PR fixes them.
> CMS setup tests fix

- .changeset/seven-sheep-watch.md
- apps/emails-and-messages/src/modules/mjml/configuration/mjml-config-container.ts
- apps/emails-and-messages/src/modules/mjml/configuration/mjml-config-input-schema.ts
- apps/emails-and-messages/src/modules/mjml/configuration/mjml-config.ts
- apps/emails-and-messages/src/modules/mjml/configuration/ui/mjml-configuration-form.tsx
- apps/emails-and-messages/src/modules/mjml/send-email-with-smtp.ts
- apps/emails-and-messages/src/modules/mjml/send-mjml.ts
Auth credentials were not passed earlier.
> Add SMTP server auth

- .changeset/few-tips-shake.md
- .changeset/purple-avocados-sip.md
- .changeset/tough-badgers-argue.md
- apps/cms/package.json
- apps/cms/src/pages/api/manifest.ts
- apps/data-importer/package.json
- apps/data-importer/src/pages/api/manifest.ts
- apps/emails-and-messages/package.json
- apps/emails-and-messages/src/modules/trpc/trpc-server.ts
- apps/emails-and-messages/src/pages/api/manifest.ts
- apps/invoices/package.json
- apps/invoices/src/modules/trpc/trpc-server.ts
- apps/invoices/src/pages/api/manifest.ts
- apps/klaviyo/package.json
- apps/monitoring/package.json
- apps/products-feed/package.json
- apps/products-feed/src/modules/trpc/trpc-server.ts
- apps/products-feed/src/pages/api/manifest.ts
- apps/search/package.json
- apps/search/src/pages/api/configuration.ts
- apps/search/src/pages/api/manifest.ts
- apps/slack/package.json
- apps/slack/src/lib/slack.ts
- apps/slack/src/pages/api/manifest.ts
- apps/slack/src/pages/api/webhooks/order-created.ts
- apps/taxes/package.json
- apps/taxes/src/modules/trpc/trpc-server.ts
- apps/taxes/src/pages/api/manifest.ts
- pnpm-lock.yaml
> Author field in manifests

- apps/cms/graphql/queries/FetchProductVariantMetadata.graphql
- apps/cms/src/lib/cms/client/clients-operations.test.ts
- apps/cms/src/lib/cms/client/clients-operations.ts
- apps/cms/src/lib/cms/config/providers.ts
- apps/cms/src/lib/metadata.ts
- apps/cms/src/modules/channels/ui/channel-configuration-form.tsx
- apps/cms/src/modules/channels/ui/channel-configuration.tsx
- apps/cms/src/modules/provider-instances/ui/provider-instance-configuration-form.tsx
- apps/cms/src/modules/provider-instances/ui/provider-instance-configuration.tsx
- apps/cms/src/modules/provider-instances/ui/provider-instances-list-items.tsx
- apps/cms/src/modules/provider-instances/ui/provider-instances-list.tsx
- apps/cms/src/modules/ui/instructions.tsx
- apps/cms/src/pages/api/webhooks/product-variant-created.ts
- apps/cms/src/pages/api/webhooks/product-variant-deleted.ts
- apps/cms/src/pages/api/webhooks/product-variant-updated.ts
It introduces:
- UI updates,
- fetching current metadata to check existing CMS providers against, instead of relying on metadata from the payload, which can be outdated if webhook events delivery has been retried after long period of time
> CMS UI and webhook updates

- .changeset/small-parrots-listen.md
- apps/products-feed/graphql/fragments/CategoryWithMappingFragment.graphql
- apps/products-feed/graphql/fragments/GoogleFeedProductVariantFragment.graphql
- apps/products-feed/graphql/mutations/UpdateCategoryMapping.graphql
- apps/products-feed/graphql/queries/FetchCategoriesWithMapping.graphql
- apps/products-feed/package.json
- apps/products-feed/src/lib/google-feed/generate-google-xml-feed.ts
- apps/products-feed/src/lib/google-feed/product-to-proxy.ts
- apps/products-feed/src/modules/app-configuration/ui/channels-configuration.tsx
- apps/products-feed/src/modules/category-mapping/category-mapping-input-schema.ts
- apps/products-feed/src/modules/category-mapping/category-mapping.router.ts
- apps/products-feed/src/modules/category-mapping/google-product-categories.ts
- apps/products-feed/src/modules/category-mapping/ui/category-mapping-form.tsx
- apps/products-feed/src/modules/category-mapping/ui/category-mapping.tsx
- apps/products-feed/src/modules/category-mapping/ui/instructions.tsx
- apps/products-feed/src/modules/trpc/trpc-app-router.ts
- apps/products-feed/src/modules/ui/configuration-page-base-layout.tsx
- apps/products-feed/src/pages/api/manifest.ts
- apps/products-feed/src/pages/categories.tsx
- pnpm-lock.yaml
> Add Google Category Mapping for the feed

- .changeset/clean-dragons-jump.md
- apps/products-feed/README.md
- apps/products-feed/src/pages/api/feed/[url]/[channel]/google.xml.ts
- turbo.json
Sets default cache time for 5 minutes
> Add cache to products feed

- apps/cms/turbo.json
- apps/crm/turbo.json
- apps/data-importer/turbo.json
- apps/emails-and-messages/turbo.json
- apps/invoices/turbo.json
- apps/klaviyo/turbo.json
- apps/monitoring/turbo.json
- apps/products-feed/turbo.json
- apps/search/turbo.json
- apps/slack/turbo.json
- apps/taxes/turbo.json
- package.json
- packages/eslint-config-saleor/package.json
- pnpm-lock.yaml
- turbo.json
Moves top level turbo.json to local, per-app config based on turbo 1.9
> Change turborepo config to use local turbo.json

- .changeset/loud-taxis-end.md
- .changeset/rare-tigers-agree.md
- apps/invoices/package.json
- apps/invoices/src/lib/saleor-version-compatibility-validator.test.ts
- apps/invoices/src/lib/saleor-version-compatibility-validator.ts
- apps/invoices/src/modules/trpc/protected-client-procedure.ts
- apps/invoices/src/pages/api/manifest.ts
- apps/invoices/src/pages/api/register.ts
- apps/invoices/src/pages/api/webhooks/invoice-requested.ts
- apps/invoices/src/saleor-app.ts
- apps/invoices/turbo.json
- pnpm-lock.yaml
It extracts logic on app's side that ensures Saleor Version is valid. It should be probably extracted to shared package in monorepo (maybe entire "hook"), or maybe even to the SDK itself.
> Improves how Saleor version is validated during installation (Invoices)

- .changeset/sour-deers-camp.md
- apps/cms/src/lib/cms/config/providers.ts
- apps/cms/src/pages/api/sync-products-variants.ts
Some small fixes for https://github.com/saleor/apps/issues/372
> CMS visual fixes

- .github/workflows/unit-tests.yml
- apps/data-importer/package.json
- apps/invoices/package.json
- package.json
> Change test script to be "test" instead "test:ci" so all tests are executed properly

- .changeset/strong-peas-begin.md
- apps/products-feed/graphql/queries/FetchProductCursors.graphql
- apps/products-feed/src/lib/google-feed/fetch-product-data.ts
Speed up feed generation by running heavy queries in parallel.
> Parallel products feed data fetching

- .changeset/eleven-adults-explain.md
I've forgot to add changeset [in the last PR](https://github.com/saleor/apps/pull/478)
> Add missing changeset to the Products Feed app

- .changeset/real-dragons-talk.md
- packages/react-hook-form-macaw/index.ts
- packages/react-hook-form-macaw/src/components/Select.stories.tsx
- packages/react-hook-form-macaw/src/components/Select.tsx
Add Select component which can be controlled by RHF.
> Add bindings for Select component

- .changeset/happy-rocks-draw.md
- .changeset/swift-boxes-drop.md
- apps/cms/package.json
- apps/crm/package.json
- apps/crm/src/lib/metadata-manager.ts
- apps/crm/src/modules/mailchimp/mailchimp-audience.router.ts
- apps/crm/src/modules/mailchimp/mailchimp-config-settings-manager.test.ts
- apps/crm/src/modules/mailchimp/mailchimp-config-settings-manager.ts
- apps/crm/src/modules/mailchimp/mailchimp-config.router.ts
- apps/crm/src/pages/api/webhooks/customer-created.ts
- apps/crm/src/pages/api/webhooks/customer-updated.ts
- apps/data-importer/package.json
- apps/emails-and-messages/package.json
- apps/invoices/package.json
- apps/klaviyo/package.json
- apps/monitoring/package.json
- apps/products-feed/package.json
- apps/search/package.json
- apps/slack/package.json
- apps/taxes/package.json
- packages/eslint-config-saleor/package.json
- packages/shared/package.json
- packages/ui/package.json
- pnpm-lock.yaml
Previously metadata was set to undefined. Now app used new SDK with metadata manager's `delete` method
> Add removing metadata in CRM app

- .github/workflows/check-deps.yml
- .syncpackrc
- package.json
- pnpm-lock.yaml
- adds [`syncpack`](https://github.com/JamieMason/syncpack) - a toolset for managing dependencies in JavaScript monorepos (versions and formatting)
- adds `check-deps` script in `package.json`~, executes it `postinstall`~
- ~runs the script on all the apps~
- adds GitHub Action that:
1.  Runs `syncpack` on each PR
2. ~Commits the changes to the PR~ Lists all the version mismatches in a comment without blocking the merge
If anything breaks during the dependencies upgrade, the assignee has to manually fix it.
> feat: align monorepo deps automatically

- .github/workflows/build-and-publish-monitoring-backend.yml
Create workflow to build and publish backend image for monitoring application
> Create workflow to build image for monitoring backend

- apps/emails-and-messages/package.json
- apps/emails-and-messages/scripts/migrations/README.md
- apps/emails-and-messages/scripts/migrations/migration-utils.ts
- apps/emails-and-messages/scripts/migrations/run-migration.ts
- apps/emails-and-messages/scripts/migrations/run-report.ts
- pnpm-lock.yaml
Applies migration to environments saved in the APL.
Use migrations [from this PR](https://github.com/saleor/apps/pull/535)
> 📧 Migration script to schema V2

- .changeset/odd-berries-think.md
- apps/emails-and-messages/src/components/box-footer.tsx
- apps/emails-and-messages/src/components/section-with-description.tsx
- apps/emails-and-messages/src/modules/app-configuration/ui/messaging-providers-box.tsx
- apps/emails-and-messages/src/modules/app-configuration/ui/provider-selection-box.tsx
- apps/emails-and-messages/src/modules/channels/ui/universal-channels-section.tsx
- apps/emails-and-messages/src/modules/sendgrid/ui/sendgrid-dangerous-section.tsx
- apps/emails-and-messages/src/modules/sendgrid/ui/sendgrid-logo.tsx
- apps/emails-and-messages/src/modules/smtp/ui/smtp-dangerous-section.tsx
- apps/emails-and-messages/src/modules/smtp/ui/smtp-logo.tsx
- apps/emails-and-messages/src/pages/configuration/choose-provider.tsx
- apps/emails-and-messages/src/pages/configuration/sendgrid/[configurationId].tsx
- apps/emails-and-messages/src/pages/configuration/smtp/[configurationId].tsx
- apps/search/src/views/configuration/configuration.view.tsx
- Gaps between danger section paragraphs 
- Gap between section title and its description. Also between framed box and description
- Provider selection boxes have limited width and added logos
- Fixed color of the pressed delete button
- Removed text above add your first configuration button
> 📧 Improve layout and white-space

- .changeset/odd-berries-think.md
- .changeset/polite-badgers-relate.md
- .changeset/popular-comics-sniff.md
- apps/emails-and-messages/src/components/box-footer.tsx
- apps/emails-and-messages/src/components/section-with-description.tsx
- apps/emails-and-messages/src/modules/app-configuration/ui/configuration-active-description-text.tsx
- apps/emails-and-messages/src/modules/app-configuration/ui/configuration-name-description-text.tsx
- apps/emails-and-messages/src/modules/app-configuration/ui/messaging-providers-box.tsx
- apps/emails-and-messages/src/modules/app-configuration/ui/provider-selection-box.tsx
- apps/emails-and-messages/src/modules/channels/ui/universal-channels-section.tsx
- apps/emails-and-messages/src/modules/sendgrid/ui/api-connection-section.tsx
- apps/emails-and-messages/src/modules/sendgrid/ui/sendgrid-api-key-description-text.tsx
- apps/emails-and-messages/src/modules/sendgrid/ui/sendgrid-basic-information-section.tsx
- apps/emails-and-messages/src/modules/sendgrid/ui/sendgrid-dangerous-section.tsx
- apps/emails-and-messages/src/modules/sendgrid/ui/sendgrid-events-section.tsx
- apps/emails-and-messages/src/modules/sendgrid/ui/sendgrid-logo.tsx
- apps/emails-and-messages/src/modules/sendgrid/ui/sendgrid-sender-section.tsx
- apps/emails-and-messages/src/modules/smtp/ui/smtp-basic-information-section.tsx
- apps/emails-and-messages/src/modules/smtp/ui/smtp-dangerous-section.tsx
- apps/emails-and-messages/src/modules/smtp/ui/smtp-events-section.tsx
- apps/emails-and-messages/src/modules/smtp/ui/smtp-logo.tsx
- apps/emails-and-messages/src/modules/smtp/ui/smtp-section.tsx
- apps/emails-and-messages/src/modules/smtp/ui/smtp-sender-section.tsx
- apps/emails-and-messages/src/pages/configuration/choose-provider.tsx
- apps/emails-and-messages/src/pages/configuration/index.tsx
- apps/emails-and-messages/src/pages/configuration/sendgrid/[configurationId].tsx
- apps/emails-and-messages/src/pages/configuration/sendgrid/new.tsx
- apps/emails-and-messages/src/pages/configuration/smtp/[configurationId].tsx
- apps/emails-and-messages/src/pages/configuration/smtp/new.tsx
- apps/search/src/views/configuration/configuration.view.tsx
- extracted descriptions if shared between views
- improved description copy
> 📧 Improve section descriptions

- apps/taxes/src/modules/avatax/avatax-connection-schema.ts
- apps/taxes/src/modules/avatax/ui/avatax-configuration-form.tsx
- apps/taxes/src/modules/channel-configuration/ui/channel-table.tsx
- apps/taxes/src/modules/ui/provider-label.tsx
- apps/taxes/src/pages/providers/index.tsx
- packages/react-hook-form-macaw/src/components/Toggle.tsx
- shipping tax code field in Avatax
- some minor visual adjustments & fixes
> feat: shipping tax code

- .changeset/tricky-rings-beam.md
- apps/search/src/components/AlgoliaConfigurationForm.tsx
Fixes regression after refactoring form inputs
> Changed index prefix in algolia to be optional

- .github/PULL_REQUEST_TEMPLATE.md
- .github/dependabot.yaml
This tells dependabot where to find all the packages as currently it does not know there are 17 packages.
> Add dependabot configuration file

- .changeset/poor-needles-burn.md
- apps/emails-and-messages/src/modules/sendgrid/ui/api-connection-section.tsx
- apps/emails-and-messages/src/modules/sendgrid/ui/sendgrid-events-section.tsx
- apps/emails-and-messages/src/pages/configuration/sendgrid/new.tsx
- add space between docs link and the rest of the text in the events section description
- use proper helper text for API key input
> 📧 Improve descriptions

- .changeset/ninety-plums-look.md
- .changeset/poor-hounds-move.md
- apps/products-feed/src/modules/category-mapping/construct-category-breadcrumbs.tsx
- apps/products-feed/src/modules/category-mapping/ui/category-mapping-form.tsx
- apps/products-feed/src/modules/category-mapping/ui/category-mapping.tsx
- apps/products-feed/src/pages/categories.tsx
- apps/products-feed/src/pages/configuration.tsx
Add test-id attributes to several elements for better e2e testing
> Add test-ids to product feed

- .changeset/famous-trees-work.md
- apps/invoices/next.config.js
- apps/invoices/sentry.client.config.ts
- apps/invoices/sentry.edge.config.ts
- apps/invoices/sentry.server.config.ts
- apps/invoices/src/modules/app-configuration/app-configuration-router.ts
- apps/invoices/src/modules/app-configuration/ui/address-form.tsx
- apps/invoices/src/pages/api/webhooks/invoice-requested.ts
Add manual breadcrumbs in invoice created webhook, so Sentry can trace what happened before error
> Improve errors handling in Invoices app

- .changeset/heavy-dragons-promise.md
- apps/klaviyo/src/pages/_app.tsx
https://saleor.sentry.io/issues/4280613622/?project=4504530225725440&rule_id=13497868
> Disabled Klaviyo ssr

- .changeset/yellow-badgers-promise.md
- apps/cms/.env.example
- apps/cms/src/pages/api/manifest.ts
- apps/cms/turbo.json
- apps/crm/.env.example
- apps/crm/src/pages/api/manifest.ts
- apps/crm/turbo.json
- apps/data-importer/.env.example
- apps/data-importer/src/pages/api/manifest.ts
- apps/data-importer/turbo.json
- apps/emails-and-messages/.env.example
- apps/emails-and-messages/src/pages/api/manifest.ts
- apps/emails-and-messages/turbo.json
- apps/invoices/.env.example
- apps/invoices/src/pages/api/manifest.ts
- apps/invoices/turbo.json
- apps/klaviyo/.env.example
- apps/monitoring/turbo.json
- apps/products-feed/.env.example
- apps/products-feed/src/pages/api/manifest.ts
- apps/products-feed/turbo.json
- apps/search/.env.example
- apps/search/src/pages/api/manifest.ts
- apps/search/turbo.json
- apps/slack/.env.example
- apps/slack/src/pages/api/manifest.ts
- apps/slack/turbo.json
- apps/taxes/.env.example
- apps/taxes/src/pages/api/manifest.ts
- apps/taxes/turbo.json
updates apps to work of the box with this doc https://docs.saleor.io/docs/3.x/developer/extending/apps/local-app-development
> Update menifests to reflect dynamic urls from env

- .changeset/tough-dingos-rule.md
- apps/emails-and-messages/src/modules/event-handlers/send-event-messages.ts
- apps/emails-and-messages/src/modules/sendgrid/send-sendgrid.ts
- apps/emails-and-messages/src/modules/smtp/send-email-with-smtp.ts
- apps/emails-and-messages/src/modules/smtp/send-smtp.ts
SMTP transport uses now proper configuration based on chosen configuration.
Related: #686
> 📧 Fix for setting up SMTP transport

- .changeset/four-walls-rhyme.md
- apps/cms/package.json
- apps/crm/package.json
- apps/data-importer/package.json
- apps/emails-and-messages/package.json
- apps/invoices/package.json
- apps/klaviyo/package.json
- apps/monitoring/package.json
- apps/products-feed/package.json
- apps/search/package.json
- apps/slack/package.json
- apps/taxes/package.json
- package.json
- packages/eslint-config-saleor/package.json
- packages/react-hook-form-macaw/package.json
- packages/shared/package.json
- packages/ui/package.json
- pnpm-lock.yaml
> Update TS and ESLint

- .changeset/nasty-mugs-divide.md
- apps/cms/package.json
- apps/crm/package.json
- apps/data-importer/package.json
- apps/emails-and-messages/package.json
- apps/invoices/package.json
- apps/klaviyo/package.json
- apps/monitoring/package.json
- apps/products-feed/package.json
- apps/search/package.json
- apps/slack/package.json
- apps/taxes/package.json
- packages/e2e/package.json
- packages/shared/package.json
- packages/ui/package.json
- pnpm-lock.yaml
Updated the @saleor/app-sdk package to version 0.41.1.
> Update the app sdk package

- .changeset/rare-snails-press.md
- apps/cms-v2/src/modules/providers/builder.io/builder-io-config-form.tsx
> CMS: mask api key inputs in builder io form

- .changeset/eight-windows-turn.md
- apps/emails-and-messages/src/lib/notify-event-types.ts
- apps/emails-and-messages/src/modules/event-handlers/default-payloads.ts
- apps/emails-and-messages/src/modules/event-handlers/message-event-types.ts
- apps/emails-and-messages/src/modules/smtp/default-templates.ts
- apps/emails-and-messages/src/modules/webhook-management/webhook-management-service.ts
- apps/emails-and-messages/src/modules/webhook-management/webhook-status-dict.ts
- apps/emails-and-messages/src/pages/api/webhooks/notify.ts
Added for the event sent when fulfillment is updated (for example when tracing code is added)
#729
> EAM: Fulfillment updated event

- README.md
Adds the Saleor Community link to the README
N/A
> Add Discord to the README

- .changeset/friendly-planets-care.md
- apps/search/graphql/fragments/ProductData.graphql
- apps/search/graphql/fragments/ProductVariantData.graphql
- apps/search/src/lib/algolia/algoliaUtils.ts
- apps/search/src/lib/algolia/metadata-to-algolia-attribute.test.ts
- apps/search/src/lib/algolia/metadata-to-algolia-attribute.ts
- apps/search/src/lib/safe-parse-json.ts
- apps/search/src/pages/api/webhooks/saleor/product_variant_updated.ts
Fixes:
https://github.com/saleor/apps/issues/774
https://github.com/saleor/apps/issues/775
> Improve Search/Algolia mappings

- .changeset/forty-onions-wash.md
- .changeset/nine-dryers-wink.md
- apps/products-feed/graphql/fragments/AttributeWithMappingFragment.graphql
- apps/products-feed/graphql/fragments/GoogleFeedProductVariantFragment.graphql
- apps/products-feed/graphql/queries/FetchAttributesWithMapping.graphql
- apps/products-feed/src/modules/app-configuration/app-config.test.ts
- apps/products-feed/src/modules/app-configuration/app-config.ts
- apps/products-feed/src/modules/app-configuration/app-configuration.router.ts
- apps/products-feed/src/modules/app-configuration/attribute-fetcher.ts
- apps/products-feed/src/modules/app-configuration/attribute-mapping-form.tsx
- apps/products-feed/src/modules/google-feed/attribute-mapping.test.ts
- apps/products-feed/src/modules/google-feed/attribute-mapping.ts
- apps/products-feed/src/modules/google-feed/generate-google-xml-feed.test.ts
- apps/products-feed/src/modules/google-feed/generate-google-xml-feed.ts
- apps/products-feed/src/modules/google-feed/get-google-feed-settings.test.ts
- apps/products-feed/src/modules/google-feed/get-google-feed-settings.ts
- apps/products-feed/src/modules/google-feed/product-to-proxy.test.ts
- apps/products-feed/src/modules/google-feed/product-to-proxy.ts
- apps/products-feed/src/modules/google-feed/types.ts
- apps/products-feed/src/pages/api/feed/[url]/[channel]/google.xml.ts
- apps/products-feed/src/pages/configuration.tsx
Use product ID as Item Group ID in the generated feed and variant ID as item id.
> Product Feed: Add group ID

- .changeset/pink-dolphins-collect.md
- apps/cms-v2/package.json
- apps/crm/package.json
- apps/data-importer/package.json
- apps/emails-and-messages/package.json
- apps/invoices/package.json
- apps/invoices/src/modules/invoices/invoice-file-name/hash-invoice-filename.test.ts
- apps/invoices/vitest.config.ts
- apps/klaviyo/package.json
- apps/products-feed/package.json
- apps/search/package.json
- apps/slack/package.json
- apps/taxes/package.json
- package.json
- packages/eslint-config-saleor/package.json
- packages/react-hook-form-macaw/package.json
- packages/shared/package.json
- packages/ui/package.json
- pnpm-lock.yaml
- syncpack.config.js
> Update dev dependencies

- .changeset/nervous-tables-agree.md
- .changeset/poor-mugs-fix.md
- .changeset/tasty-icons-drum.md
- apps/products-feed/src/modules/app-configuration/app-config.test.ts
- apps/products-feed/src/modules/app-configuration/app-config.ts
- apps/products-feed/src/modules/app-configuration/app-configuration.router.ts
- apps/products-feed/src/modules/app-configuration/channels/channels.router.ts
- apps/products-feed/src/modules/app-configuration/title-formatting-form.tsx
- apps/products-feed/src/modules/trpc/middlewares.ts
- apps/products-feed/src/modules/trpc/protected-client-procedure.ts
Fixes 2 errors found after latest release:
- title edit form did not save the data
- when data from last version have been saved in the metadata, parsing function would fail
Besides that added more roboust logging
> Product feed: Fix title template form

- .changeset/eleven-bears-end.md
- apps/cms-v2/package.json
- apps/crm/package.json
- apps/data-importer/package.json
- apps/emails-and-messages/package.json
- apps/invoices/package.json
- apps/klaviyo/package.json
- apps/products-feed/package.json
- apps/search/package.json
- apps/segment/package.json
- apps/slack/package.json
- apps/taxes/package.json
- packages/react-hook-form-macaw/package.json
- packages/shared/package.json
- packages/ui/package.json
- pnpm-lock.yaml
> update macaw to pre-118

- .changeset/great-mice-lie.md
- .changeset/itchy-games-hear.md
- apps/cms-v2/src/modules/configuration/metadata-manager.ts
- apps/cms-v2/src/setup-tests.ts
- apps/invoices/src/modules/app-configuration/__mocks__/metadata-manager.ts
- apps/search/src/test/handlers/webhooks-status-handler.test.ts
- apps/segment/src/modules/configuration/metadata-manager.ts
- packages/shared/index.ts
- packages/shared/package.json
- packages/shared/src/metadata-manager.ts
- pnpm-lock.yaml
1. Extract metadata-manager (copy-pasted in all apps) to shared package
2. Used this factory in cms-2 and segment apps (no-config change)
Other apps must be updated in further PRs, due to some refactor needed (e.g. appId must be present)
> add metadata manager to shared package

- .changeset/thick-pots-crash.md
- apps/segment/src/modules/tracking-events/tracking-events.ts
docs
https://github.com/saleor/saleor-docs/pull/888
> Changed events mapping in Segment

- .changeset/hungry-clocks-move.md
- apps/cms-v2/src/modules/providers/payloadcms/payloadcms-config-form.tsx
> fix payloadcms fields

- .changeset/proud-cheetahs-pay.md
- apps/cms-v2/src/modules/theme/styles.css
> Fix CMS modal bg

- .changeset/moody-frogs-bow.md
- apps/search/graphql/fragments/OwnWebhook.graphql
- apps/search/graphql/queries/FetchOwnWebhooks.graphql
- apps/search/package.json
- apps/search/scripts/migrations/README.md
- apps/search/scripts/migrations/migration-utils.ts
- apps/search/scripts/migrations/recreate-webhooks.ts
- apps/search/scripts/migrations/run-webhooks-migration-dry-run.ts
- apps/search/scripts/migrations/run-webhooks-migration.ts
- pnpm-lock.yaml
Add command line script to update webhooks
> Search: webhooks migration script

- .changeset/happy-colts-cough.md
- .changeset/kind-wombats-beg.md
- .changeset/metal-worms-double.md
- apps/search/src/components/AlgoliaConfigurationForm.tsx
- apps/search/src/domain/configuration.ts
- apps/search/src/lib/algolia/getAlgoliaConfiguration.ts
- apps/search/src/lib/algolia/is-configured.ts
- apps/search/src/modules/configuration/app-config-metadata-manager.ts
- apps/search/src/modules/configuration/configuration.router.ts
- apps/search/src/modules/configuration/configuration.ts
- apps/search/src/modules/configuration/legacy-configuration.ts
- apps/search/src/pages/api/manifest.ts
- apps/search/src/pages/api/webhooks/saleor/product_created.ts
- apps/search/src/pages/api/webhooks/saleor/product_deleted.ts
- apps/search/src/pages/api/webhooks/saleor/product_updated.ts
- apps/search/src/pages/api/webhooks/saleor/product_variant_back_in_stock.ts
- apps/search/src/pages/api/webhooks/saleor/product_variant_created.ts
- apps/search/src/pages/api/webhooks/saleor/product_variant_deleted.ts
- apps/search/src/pages/api/webhooks/saleor/product_variant_out_of_stock.ts
- apps/search/src/pages/api/webhooks/saleor/product_variant_updated.ts
- apps/search/src/webhooks/webhook-context.ts
> Refactors: webhooks, config

- .changeset/hot-eagles-cheer.md
- apps/products-feed/src/modules/app-configuration/image-configuration-form.tsx
Remove leftover debug message from the button label.
> Product Feed: Fix save button label

- .changeset/angry-ravens-enjoy.md
- apps/search/src/components/AlgoliaConfigurationForm.tsx
- apps/search/src/components/AlgoliaFieldsSelectionForm.tsx
- apps/search/src/components/ImportProductsToAlgolia.tsx
- apps/search/src/components/IndicesSettings.tsx
- apps/search/src/domain/WebhookActivityToggler.service.test.ts
- apps/search/src/lib/algolia-fields.ts
- apps/search/src/lib/algolia/algoliaSearchProvider.ts
- apps/search/src/lib/algolia/algoliaUtils.ts
- apps/search/src/modules/configuration/configuration.router.ts
- apps/search/src/modules/configuration/configuration.ts
- apps/search/src/pages/api/setup-indices.ts
- apps/search/src/pages/api/webhooks-status.ts
- apps/search/src/views/configuration/configuration.view.tsx
- apps/search/src/webhooks/webhook-context.ts
- cspell.json
Quick implementation of fields filtering. Code requires some refactor, due to some internal coupling. 
Will proceed in further PRs. Basic functionality is delivered
> Algolia fields filtering

- cspell.json
- package.json
- added more ignored paths
- fixed a bug when check fails when no files found
> refactor: :recycle: omit more in cspell config

- apps/search/src/pages/api/recreate-webhooks.ts
- apps/search/src/pages/api/webhooks-status.ts
- apps/search/src/test/handlers/webhooks-status-handler.test.ts
> Fix Search webhooks toggling

- .changeset/mighty-tips-hug.md
- apps/cms-v2/package.json
- apps/crm/package.json
- apps/data-importer/package.json
- apps/emails-and-messages/package.json
- apps/invoices/package.json
- apps/klaviyo/package.json
- apps/products-feed/package.json
- apps/search/package.json
- apps/segment/package.json
- apps/slack/package.json
- apps/taxes/package.json
- package.json
- pnpm-lock.yaml
Sentry CLI in the workspace should fix sourcemaps uploading on build
> Update sentry and add Sentry CLI to the workspace

- package.json
- pnpm-lock.yaml
It changes version of pnpm that will be used in github actions
> Update pnpm version expected by the monorepo

- pnpm-lock.yaml
Fix broken pnpm lock when run with `pnpm install --frozen-lockfile` in CICD
> Fix broken pnpm lock

- .github/workflows/changeset-checker.yml
- .github/workflows/check-deps.yml
- .github/workflows/check-spelling.yml
- .github/workflows/prepare-release.yml
- .github/workflows/unit-tests.yml
> Use full commit hash when referencing GitHub Action

- .changeset/nice-points-allow.md
- apps/taxes/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-adapter.ts
- apps/taxes/src/modules/avatax/order-cancelled/avatax-order-cancelled-adapter.ts
- apps/taxes/src/modules/avatax/order-confirmed/avatax-order-confirmed-adapter.ts
- apps/taxes/src/modules/logs/client-logger.ts
- apps/taxes/src/modules/logs/ui/client-logs-page.tsx
- apps/taxes/src/modules/taxjar/calculate-taxes/taxjar-calculate-taxes-adapter.ts
- apps/taxes/src/modules/taxjar/order-confirmed/taxjar-order-confirmed-adapter.ts
fixes: https://github.com/saleor/apps/issues/1026
> refactor: limit Taxes App client side logs to failures

- .changeset/angry-roses-push.md
- apps/products-feed/src/pages/api/feed/[url]/[channel]/google.xml.ts
- apps/products-feed/vercel.json
Update lambda execution limit using vercel.json
> Add vercel json file with lambda execution limits

- .changeset/fast-geese-nail.md
- apps/search/vercel.json
> reduce update webhooks memory limits

- .changeset/old-cobras-greet.md
- apps/cms-v2/package.json
- apps/crm/package.json
- apps/data-importer/package.json
- apps/emails-and-messages/package.json
- apps/invoices/package.json
- apps/klaviyo/package.json
- apps/products-feed/package.json
- apps/search/package.json
- apps/segment/package.json
- apps/slack/package.json
- apps/taxes/package.json
- pnpm-lock.yaml
Update Sentry to the newest version
> Update sentry to 7.77.0

- .changeset/few-chicken-explode.md
- .changeset/four-beans-trade.md
- apps/cms-v2/package.json
- apps/crm/package.json
- apps/data-importer/package.json
- apps/emails-and-messages/package.json
- apps/invoices/package.json
- apps/klaviyo/package.json
- apps/products-feed/package.json
- apps/search/package.json
- apps/segment/package.json
- apps/slack/package.json
- apps/taxes/package.json
- package.json
- packages/e2e/package.json
- packages/shared/package.json
- packages/trpc/package.json
- packages/ui/package.json
- packages/webhook-utils/package.json
- pnpm-lock.yaml
> Update and unify deps to fix app-bridge resolution

- .changeset/loud-spies-jump.md
- package.json
- pnpm-lock.yaml
> update app-sdk to 0.47.2

- .changeset/modern-ducks-count.md
- apps/slack/vercel.json
> reduce slack app memory

- .changeset/odd-crabs-care.md
- apps/cms-v2/vercel.json
> reduce cms ram limit in vercel

- .changeset/tough-mails-care.md
- apps/slack/src/lib/is-valid-url.test.ts
- apps/slack/src/lib/is-valid-url.ts
- apps/slack/src/pages/api/configuration.ts
- apps/slack/src/pages/configuration.tsx
> fix url validation and configuration setting

- .changeset/tricky-dolls-drop.md
- apps/taxes/src/modules/taxjar/ui/taxjar-configuration-form.tsx
> Open taxjar docs link in the new tab

- README.md
> remove roadmap link

- .github/PULL_REQUEST_TEMPLATE.md
- turbo.json
> Update README with search app deployment problem

- cspell.json
> Update cspell dict with shopex

- .github/labeler.yml
> Change monorepo labels to reflect current state of apps

- .changeset/lazy-hornets-dream.md
- apps/avatax/src/modules/app/webhook-response.ts
- apps/avatax/src/modules/taxes/tax-error.ts
- apps/avatax/src/modules/webhooks/calculate-taxes-payload.ts
- apps/avatax/src/modules/webhooks/validate-webhook-payload.test.ts
- apps/avatax/src/modules/webhooks/validate-webhook-payload.ts
- apps/avatax/src/pages/api/webhooks/checkout-calculate-taxes.ts
- apps/avatax/src/pages/api/webhooks/order-calculate-taxes.ts
- pnpm-lock.yaml
> Improved error handling in cases with missing address and lines

- apps/avatax/src/modules/avatax/avatax-webhook.service.ts
- apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-adapter.ts
- apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-payload-transformer.test.ts
- apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-payload-transformer.ts
- apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-payload.service.ts
- apps/avatax/src/modules/taxes/tax-provider-webhook.ts
> Fix avatax build

- .github/workflows/e2e.yml
- apps/avatax/package.json
- apps/avatax/vitest.workspace.ts
Add avatax e2e workflow for 3.18 and 3.19 Saleor versions.
Fixes https://linear.app/saleor/issue/SHOPX-269
> Avatax app e2e workflow

- .github/workflows/e2e.yml
This PR updates e2e workflow to  use 1password action.
Fixes: https://linear.app/saleor/issue/SHOPX-303
> Update e2e to use 1pass

- .changeset/forty-balloons-do.md
- apps/avatax/vercel.json
> limit avatax app vercel resources

- apps/avatax/vercel.json
> Fix paths to webhooks vercel.json

- .changeset/perfect-rice-warn.md
- apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-adapter.ts
- apps/avatax/src/pages/api/webhooks/checkout-calculate-taxes.ts
- apps/avatax/src/pages/api/webhooks/order-calculate-taxes.ts
> Change some debug logs to info, add extra metadata

- .changeset/three-roses-hide.md
- apps/search/graphql/fragments/ProductAttributesData.graphql
- apps/search/src/lib/algolia/algoliaUtils.test.ts
- apps/search/src/lib/algolia/algoliaUtils.ts
> SHOPX-332 Add Algolia parsing boolean attribute type

- apps/avatax/vercel.json
* Increases `maxDuration` for async webhooks
> Increase vercel duration for async webhooks

- apps/avatax/scripts/migrations/run-webhooks-migration.ts
> Fix migration script for avatax

- apps/avatax/turbo.json
This PR changes turbo.json for Avatax as we have new script - `deploy`.
> Update turbo configuration for avatax

- .github/workflows/e2e.yml
> Update e2e workflow to run on label for Avatax

- .changeset/popular-geckos-jog.md
- apps/avatax/.env.example
- apps/avatax/src/modules/avatax/avatax-client.ts
- apps/avatax/turbo.json
> Increased timeout for avatax client

- .github/workflows/e2e.yml
- apps/avatax/README.md
- apps/avatax/package.json
- apps/avatax/scripts/migrations/run-webhooks-migration.ts
- apps/avatax/scripts/migrations/update-webhooks.ts
* Adds migration script to e2e workflow
* Hides sensitive information from migration script
* Fixes issue when we don't allow manual workflow trigger
> Add migration script to e2e workflow

- .changeset/new-bugs-mate.md
- packages/logger/src/logger-sentry-transport.ts
> Change Sentry breadcrumb timestamp to integer

- .changeset/witty-ravens-tie.md
- apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-adapter.ts
- apps/avatax/src/modules/taxes/tax-error.ts
- apps/avatax/src/pages/api/webhooks/checkout-calculate-taxes.ts
- apps/avatax/src/pages/api/webhooks/order-calculate-taxes.ts
Adds handling for specific error that was reported to sentry incorrectly (user error). 
This PR add temporary handling where possible, but it requires further refactor
> Avatax: Add handling of TaxExternalError related to invalid zip code

- apps/avatax/sentry.client.config.ts
- apps/avatax/sentry.edge.config.ts
- apps/avatax/sentry.server.config.ts
- apps/avatax/src/lib/app-metadata-cache.ts
- apps/avatax/src/release-utils.ts
- apps/avatax/turbo.json
- packages/logger/src/logger-context.ts
- turbo.json
* Fixed logger copy
* Sentry should have proper version from pkg.json
* Check for OTEL in logger context
> Fix store logs & sentry pkg.json

- .changeset/spicy-pumas-fetch.md
- apps/avatax/src/modules/taxes/get-active-connection-service-errors.ts
- apps/avatax/src/modules/taxes/get-active-connection-service.test.ts
- apps/avatax/src/modules/taxes/get-active-connection-service.ts
- apps/avatax/src/pages/_app.tsx
- apps/avatax/src/pages/api/webhooks/checkout-calculate-taxes.ts
- apps/avatax/src/pages/api/webhooks/order-calculate-taxes.ts
- apps/avatax/src/pages/api/webhooks/order-cancelled.ts
- apps/avatax/src/pages/api/webhooks/order-confirmed.ts
Dynamically load code that calculates taxes, so its not loaded when handler returns early (incomplete payload).
If this scenario happens inside the cold start, it reduces load time by ~7s
> Dynamically load taxes calculation logic

- .github/workflows/prepare-release.yml
This will help with releasing - bot will post link to our Notion checklist
> Update release workflow with link to checklist

- .changeset/warm-ligers-jam.md
- apps/avatax/src/modules/trpc/trpc-server.ts
- apps/avatax/src/pages/api/trpc/[trpc].ts
> Add Sentry to tRPC

- apps/avatax/bruno/5._Update_checkout_metadata.bru
- apps/avatax/bruno/6_Update_delivery_method.bru
- apps/avatax/bruno/7_Complete_checkout.bru
> Add bruno request for checkout metadata

- .changeset/soft-fireants-shop.md
- apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-response-shipping-transformer.ts
> change missing shipping warning

- .changeset/lazy-swans-type.md
- apps/avatax/src/modules/avatax/order-cancelled/avatax-order-cancelled-adapter.ts
- apps/avatax/src/pages/api/webhooks/order-cancelled.ts
> Add logs for cancel order

- .changeset/violet-eggs-greet.md
- apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-tax-code-matcher.ts
- apps/avatax/src/modules/avatax/order-confirmed/avatax-order-confirmed-tax-code-matcher.ts
> Update tax class id matcher logs

- .changeset/chatty-roses-fold.md
- packages/logger/src/logger-otel-transport.ts
> Log empty values to OTEL

- .changeset/great-turkeys-shake.md
- apps/avatax/src/lib/error-utils.test.ts
- apps/avatax/src/lib/error-utils.ts
- apps/avatax/src/modules/avatax/ui/avatax-configuration-address-fragment.tsx
- apps/avatax/src/modules/avatax/ui/avatax-configuration-credentials-fragment.tsx
- apps/avatax/src/pages/api/webhooks/checkout-calculate-taxes.ts
- apps/avatax/src/pages/api/webhooks/order-calculate-taxes.ts
- apps/avatax/src/pages/api/webhooks/order-cancelled.ts
- apps/avatax/src/pages/api/webhooks/order-confirmed.ts
Added Sentry & error logging for a case when we have an error on Saleor GraphQL subscription. It should help us in spotting issues.
> Log subscription payload errors

- packages/webhook-utils/src/webhook-migration-runner.ts
- packages/webhook-utils/src/webhook-updater.ts
> Remove double webhook migration log

- apps/avatax/e2e/tests/entire_voucher_product_without_tax_class.spec.ts
> Fix e2e for voucher

- apps/avatax/.env.example
I commented out now needed env variables so newcomers won't have errors connected e.g to having empty `PORT` variable set.
> Update env vars example

- apps/cms-v2/next.config.js
- apps/crm/next.config.js
- apps/data-importer/next.config.js
- apps/emails-and-messages/next.config.js
- apps/invoices/next.config.js
- apps/klaviyo/next.config.js
- apps/products-feed/next.config.js
- apps/search/next.config.js
- apps/segment/next.config.js
- apps/slack/next.config.js
- apps/smtp/next.config.js
> Port OTEL mute to other apps

- .github/labeler.yml
- CODEOWNERS
> add SMTP codeowners and github label

- apps/smtp/graphql/schema.graphql
- apps/smtp/package.json
- apps/smtp/src/pages/api/manifest.ts
> bump smtp app to use saleor 3.19

- Dockerfile
- Dockerfile.dev
- apps/avatax/README.md
- cspell.json
This PR adds dev dockerfile so developers can run avatax app without installing all JS tooling.
> Add Dockerfile for avatax app dev mode

- apps/smtp/src/lib/race-promise.ts
- apps/smtp/src/logger-context.ts
- apps/smtp/src/logger.ts
- apps/smtp/src/modules/smtp/configuration/smtp-configuration.router.ts
- apps/smtp/src/modules/smtp/services/smtp-email-sender.ts
- apps/smtp/src/pages/api/trpc/[trpc].ts
- apps/smtp/src/pages/api/webhooks/gift-card-sent.ts
- apps/smtp/src/pages/api/webhooks/invoice-sent.ts
- apps/smtp/src/pages/api/webhooks/notify.ts
- apps/smtp/src/pages/api/webhooks/order-cancelled.ts
- apps/smtp/src/pages/api/webhooks/order-confirmed.ts
- apps/smtp/src/pages/api/webhooks/order-created.ts
- apps/smtp/src/pages/api/webhooks/order-fulfilled.ts
- apps/smtp/src/pages/api/webhooks/order-fully-paid.ts
- apps/smtp/src/pages/api/webhooks/order-refunded.ts
adds extra logs, ensured datadog logs properly
> add additional logs

- .changeset/twelve-waves-explode.md
- packages/otel/package.json
- packages/otel/src/otel-wrapper.ts
- pnpm-lock.yaml
> add waitUntil to flush logs

- .changeset/polite-garlics-swim.md
> set smtp app to 1.0.0

- .changeset/witty-camels-tell.md
- apps/search/src/domain/WebhookActivityToggler.service.ts
- apps/search/src/modules/configuration/configuration.router.ts
- apps/search/src/pages/api/recreate-webhooks.ts
- apps/search/src/pages/api/register.ts
- apps/search/src/pages/api/setup-indices.ts
- apps/search/src/pages/api/webhooks-status.ts
- apps/search/src/pages/api/webhooks/saleor/product_created.ts
- apps/search/src/pages/api/webhooks/saleor/product_deleted.ts
- apps/search/src/pages/api/webhooks/saleor/product_updated.ts
- apps/search/src/pages/api/webhooks/saleor/product_variant_back_in_stock.ts
- apps/search/src/pages/api/webhooks/saleor/product_variant_created.ts
- apps/search/src/pages/api/webhooks/saleor/product_variant_deleted.ts
- apps/search/src/pages/api/webhooks/saleor/product_variant_out_of_stock.ts
- apps/search/src/pages/api/webhooks/saleor/product_variant_updated.ts
> add info logs

- .changeset/rich-carrots-deliver.md
- apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-adapter.ts
- apps/avatax/src/modules/avatax/extract-transaction-redacted-log-properties.test.ts
- apps/avatax/src/modules/avatax/extract-transaction-redacted-log-properties.ts
- apps/avatax/src/modules/avatax/order-confirmed/avatax-order-confirmed-adapter.ts
> remove shipping addresses from logs

- .changeset/famous-terms-allow.md
> Add missing changeset for updating pnpm

- apps/crm/README.md
- apps/emails-and-messages/README.md
- apps/invoices/README.md
- apps/segment/readme.MD
- apps/slack/README.md
> add notes about maintenance of legacy apps

- .changeset/clever-pianos-cheat.md
- apps/smtp/src/modules/smtp/default-templates.ts
> Fix SMTP template for account_password_reset

- .changeset/strange-lions-cheat.md
- .changeset/strong-cheetahs-sing.md
- .changeset/wise-singers-impress.md
- apps/smtp/src/lib/fetch-app-permissions.ts
- apps/smtp/src/modules/smtp/services/handlebars-template-compiler.ts
- apps/smtp/src/modules/smtp/services/smtp-email-sender.ts
- apps/smtp/src/pages/api/trpc/[trpc].ts
- apps/smtp/vercel.json
> Fixing SMTP errors and logs

- .changeset/nervous-nails-look.md
- packages/logger/package.json
- pnpm-lock.yaml
> Fix diff sentry version

- apps/avatax/e2e/tests/entire_voucher_product_without_tax_class.spec.ts
> Fix e2e for voucher - reapply discounts

- .changeset/rotten-rockets-hug.md
- apps/cms-v2/src/modules/providers/builder.io/builder-io-webhooks-processor.ts
- apps/cms-v2/src/modules/webhooks-operations/webhooks-processors-delegator.ts
- apps/cms-v2/src/pages/api/webhooks/product-variant-updated.ts
> Improve logging in cms app

- apps/smtp/src/modules/event-handlers/use-case/send-event-messages.use-case.ts
- apps/smtp/src/modules/smtp/services/email-compiler.ts
> Fix invalid import syntax

- .changeset/chilled-zoos-appear.md
- apps/avatax/src/pages/api/register.ts
> Add logs to register fn

- .changeset/pretty-dodos-explain.md
- apps/avatax/src/pages/api/webhooks/checkout-calculate-taxes.ts
- apps/avatax/src/pages/api/webhooks/order-calculate-taxes.ts
- apps/avatax/src/pages/api/webhooks/order-cancelled.ts
- apps/avatax/src/pages/api/webhooks/order-confirmed.ts
> Send JSON as error response for AvaTax

- .changeset/selfish-forks-exercise.md
- apps/cms-v2/src/modules/webhooks-operations/webhooks-processors-delegator.ts
> Log when webhook is skip due to lack of connection or provider in cms app

- .changeset/loud-buckets-melt.md
- apps/avatax/src/modules/avatax/avatax-errors-parser.ts
- apps/avatax/src/modules/taxes/tax-error.ts
- apps/avatax/src/pages/api/webhooks/order-confirmed.ts
This fixes https://saleor.sentry.io/issues/5497893205/?alert_rule_id=15021369&alert_type=issue&notification_uuid=7f15be3d-4481-4058-a409-62ff70aa976a&project=4506739316817920&referrer=slack
> Add AvaTax string length error handling

- .changeset/honest-goats-repair.md
- apps/avatax/package.json
- apps/avatax/src/pages/api/webhooks/order-confirmed.ts
- apps/cms-v2/package.json
- apps/crm/package.json
- apps/data-importer/package.json
- apps/emails-and-messages/package.json
- apps/invoices/package.json
- apps/klaviyo/package.json
- apps/products-feed/package.json
- apps/search/package.json
- apps/segment/package.json
- apps/slack/package.json
- apps/smtp/package.json
- apps/taxjar/package.json
- packages/e2e/package.json
- packages/eslint-config-saleor/package.json
- packages/logger/package.json
- packages/otel/package.json
- packages/react-hook-form-macaw/package.json
- packages/sentry-utils/package.json
- packages/shared/package.json
- packages/trpc/package.json
- packages/ui/package.json
- packages/webhook-utils/package.json
- pnpm-lock.yaml
> Update typescript to 5.4.5

- .changeset/happy-turtles-do.md
- .changeset/mean-walls-mix.md
- apps/avatax/src/modules/avatax/avatax-errors-parser.ts
- apps/avatax/src/modules/taxes/tax-error.ts
- apps/avatax/src/pages/api/webhooks/order-calculate-taxes.ts
- apps/avatax/src/pages/api/webhooks/order-confirmed.ts
> Add support for AvataxStringLengthError to order calc taxes

- .github/workflows/changeset-checker.yml
> Use PR diff instead of pnpm action for changesets

- .changeset/lovely-toys-crash.md
- Dockerfile.avatax.dev
- apps/avatax/.env.example
- apps/avatax/saleor-app.ts
- apps/avatax/turbo.json
> Add env variable for file APL

- Dockerfile.avatax.dev
Docker volume mapping will create it instead 😄
> Remove not needed dockerfile folder creation

- CODEOWNERS
Sorted alphabetically & removed non existing paths
> Cleanup codeowners file after recent updates

- apps/avatax/scripts/run-webhooks-migration.ts
> Change log in webhook migration from error to warn

- .changeset/tame-hairs-punch.md
- apps/avatax/next.config.js
- apps/avatax/vercel.json
Added changes based on https://vercel.com/guides/how-can-i-improve-serverless-function-lambda-cold-start-performance-on-vercel:
* I changed what CPU & memory we are using in Vercel dashboard and removed entries from vercel.json
* Added `bundlePagesExternals` based on guide
> Improve AvaTax functions cold-starts

- apps/avatax/vercel.json
> Remove vercel.json file

- .changeset/wet-timers-help.md
* Changes changeset from major to patch.
> SMTP: Fix Changeset 

- .github/labeler.yml
- .github/workflows/prepare-release.yml
- README.md
- apps/avatax/.env.example
- apps/avatax/README.md
- apps/avatax/bruno/bruno.json
- apps/avatax/src/modules/avatax/avatax-errors-parser.ts
- apps/avatax/src/modules/avatax/order-confirmed/avatax-order-confirmed-tax-code-matcher.test.ts
- apps/avatax/src/modules/calculate-taxes/use-case/calculate-taxes.use-case.ts
- apps/avatax/src/modules/provider-connections/ui/providers-section.tsx
- apps/avatax/src/modules/taxes/tax-error.ts
- apps/avatax/src/pages/api/manifest.ts
- apps/avatax/src/pages/api/register.ts
- apps/avatax/src/pages/configuration.tsx
- apps/avatax/src/pages/index.tsx
> Update Avatax to AvaTax

- .changeset/thin-hairs-smoke.md
- apps/products-feed/src/modules/google-feed/fetch-product-data.ts
- apps/products-feed/src/modules/google-feed/product-processing-limit.test.ts
- apps/products-feed/src/modules/google-feed/product-processing-limit.ts
> Add logger for limit status

- .changeset/shaggy-baboons-sell.md
- apps/avatax/src/modules/avatax/avatax-client-tax-code.service.ts
- apps/avatax/src/modules/avatax/tax-code/avatax-tax-codes.router.ts
- apps/avatax/src/modules/avatax/tax-code/avatax-tax-codes.service.ts
- apps/avatax/src/modules/tax-classes/tax-classes.router.ts
> Add logs around tax code matcher

- .changeset/dry-kangaroos-live.md
- apps/avatax/src/modules/avatax/ui/avatax-tax-code-matcher-table.tsx
- apps/avatax/src/modules/avatax/ui/tax-code-select.tsx
- apps/avatax/src/pages/providers/avatax/matcher.tsx
> avatax: fallback behavior for taxcode matcher missing hints

- .changeset/modern-spies-behave.md
- apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-adapter.ts
- apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-payload-lines-transformer.test.ts
- apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-response-lines-transformer.ts
- apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-response-shipping-transformer.ts
- apps/avatax/src/modules/avatax/calculate-taxes/avatax-shipping-line.ts
- apps/avatax/src/modules/avatax/order-confirmed/avatax-order-confirmed-adapter.ts
> Add logs to AvaTax logic

- .changeset/nasty-queens-ring.md
- apps/avatax/src/modules/avatax/avatax-client-tax-code.service.test.ts
- apps/avatax/src/modules/avatax/avatax-client-tax-code.service.ts
- apps/avatax/src/modules/avatax/tax-code/avatax-tax-codes.router.ts
- apps/avatax/src/modules/avatax/tax-code/avatax-tax-codes.service.ts
> Handle PermissionRequired error from avatax in tax codes fetcher

- .changeset/sour-windows-taste.md
- apps/avatax/src/modules/avatax/avatax-errors-parser.ts
- apps/avatax/src/modules/taxes/tax-error.ts
- apps/avatax/src/pages/api/webhooks/order-calculate-taxes.ts
- apps/avatax/src/pages/api/webhooks/order-confirmed.ts
Handle AvataxEntityNotFoundError error in app instead logging it to Sentry.
https://saleor.sentry.io/issues/5719521192
> Add support for AvataxEntityNotFoundError

- apps/avatax/package.json
- apps/cms-v2/package.json
- apps/data-importer/package.json
- apps/emails-and-messages/package.json
- apps/klaviyo/package.json
- apps/products-feed/package.json
- apps/search/package.json
- apps/smtp/package.json
- packages/e2e/package.json
- packages/eslint-config-saleor/package.json
- packages/logger/package.json
- packages/otel/package.json
- packages/otel/src/instrumentation.ts
- packages/react-hook-form-macaw/package.json
- packages/sentry-utils/package.json
- packages/shared/package.json
- packages/trpc/package.json
- packages/ui/package.json
- packages/webhook-utils/package.json
- pnpm-lock.yaml
> Update TypeScript to 5.5.4

- .changeset/stale-boats-smash.md
- apps/smtp/next.config.js
> Add bundle externals flag

- .changeset/purple-suits-peel.md
- apps/search/src/modules/trpc/protected-client-procedure.ts
- apps/search/src/pages/api/webhooks/saleor/product_created.ts
- apps/search/src/pages/api/webhooks/saleor/product_deleted.ts
- apps/search/src/pages/api/webhooks/saleor/product_updated.ts
- apps/search/src/pages/api/webhooks/saleor/product_variant_back_in_stock.ts
- apps/search/src/pages/api/webhooks/saleor/product_variant_created.ts
- apps/search/src/pages/api/webhooks/saleor/product_variant_deleted.ts
- apps/search/src/pages/api/webhooks/saleor/product_variant_out_of_stock.ts
- apps/search/src/pages/api/webhooks/saleor/product_variant_updated.ts
> [Search] Improve logs

- .changeset/breezy-bags-sell.md
- apps/search/src/lib/algolia/algolia-error-parser.test.ts
- apps/search/src/lib/algolia/algolia-error-parser.ts
- apps/search/src/pages/api/webhooks/saleor/product_created.ts
- apps/search/src/pages/api/webhooks/saleor/product_updated.ts
- apps/search/src/pages/api/webhooks/saleor/product_variant_created.ts
- apps/search/src/pages/api/webhooks/saleor/product_variant_updated.ts
* Handles Algolia's "Record is too big" error
> [Search] Handle record too big error

- apps/avatax/bruno/checkout/04-create-checkout.bru
> Fix Bruno create checkout api url variable

- .changeset/brown-countries-kiss.md
- apps/search/next.config.js
> Add bundle externals for search app

- .changeset/smooth-peaches-call.md
- apps/search/saleor-app.ts
- apps/search/scripts/migrations/migration-utils.ts
- apps/search/scripts/migrations/run-webhooks-migration-dry-run.ts
- apps/search/scripts/migrations/run-webhooks-migration.ts
- apps/search/scripts/migrations/update-webhooks.ts
> Stop self-disabling active webhooks

- .changeset/sixty-toes-beg.md
- apps/avatax/saleor-app.ts
> Bump avatax minimum saleor version to 3.19

- .changeset/three-pans-hug.md
- apps/cms-v2/next.config.js
- apps/data-importer/next.config.js
- apps/klaviyo/next.config.js
- apps/products-feed/next.config.js
> Enable bundlePagesExternals for rest of apps

- .changeset/chatty-ants-brake.md
- apps/avatax/src/lib/app-config.ts
> fix error with finding channels in config

- .changeset/good-kangaroos-type.md
- package.json
- pnpm-lock.yaml
> Update app sdk to 0.50.3

- .changeset/tasty-sloths-invent.md
- apps/avatax/src/modules/avatax/order-confirmed/avatax-order-confirmed-adapter.ts
- apps/avatax/src/pages/api/webhooks/checkout-calculate-taxes.ts
- apps/avatax/src/pages/api/webhooks/order-confirmed.ts
- packages/otel/src/lib/observability-attributes.ts
> add more semantic attributes to avatax order webhooks

- .changeset/poor-plums-exist.md
> Trigger deployments for SDK bump

- .changeset/stale-baboons-matter.md
> Trigger deployments for SDK bump to 0.50.3

- .changeset/six-gifts-count.md
- packages/webhook-utils/src/webhook-migration-runner.ts
> exit migration with error if it fails

- .changeset/six-gifts-count.md
- packages/webhook-utils/src/webhook-migration-runner.ts
> Revert "exit migration with error if it fails"

- .changeset/thick-poets-invite.md
- packages/logger/.eslintrc
- packages/logger/.eslintrc.cjs
- packages/logger/src/logger-otel-transport.ts
- packages/logger/src/logger.test.ts
> Revert JSON stringify for error in OTEL transport

- apps/avatax/src/modules/client-logs/logs-repository.ts
Fixes previous PR by properly fetching logs range
> fix logs querying

- .changeset/stupid-maps-raise.md
- apps/avatax/next.config.js
- apps/avatax/package.json
- pnpm-lock.yaml
> Add serverExternalPackages to AvaTax

- .changeset/red-years-drive.md
- apps/avatax/src/pages/api/webhooks/checkout-calculate-taxes.ts
- apps/avatax/src/pages/api/webhooks/order-calculate-taxes.ts
- apps/avatax/src/pages/api/webhooks/order-cancelled.ts
> Add metadata cache to all webhooks

- .changeset/tiny-trains-film.md
- apps/avatax/src/modules/avatax/avatax-errors-parser.ts
- apps/avatax/src/modules/taxes/tax-error.ts
- apps/avatax/src/pages/api/webhooks/order-cancelled.ts
> Add support for TransactionAlreadyCancelled to AvaTax

- .npmrc
- package.json
Added ability to auto install proper pnpm version: https://pnpm.io/npmrc#manage-package-manager-versions. In the next PR we can consider adding support for catalogs: https://pnpm.io/catalogs.
> Update pnpm to 9.11.0

- apps/avatax/src/pages/api/webhooks/checkout-calculate-taxes.ts
- apps/avatax/src/pages/api/webhooks/order-calculate-taxes.ts
- apps/avatax/src/pages/api/webhooks/order-cancelled.ts
- apps/avatax/src/pages/api/webhooks/order-confirmed.ts
extract webhook handlers to variable, so nesting is smaller. Less diff, less whitespace
> refactor: flatten webhooks

- .changeset/healthy-bugs-live.md
- apps/avatax/src/modules/saleor/order-confirmed/event.ts
> Billing address fixed

- apps/avatax/src/modules/saleor/order-confirmed/event.test.ts
> add test for order confirmed event

- .changeset/popular-cars-hunt.md
- apps/smtp/src/lib/bytes-to-kb.test.ts
- apps/smtp/src/lib/bytes-to-kb.ts
- apps/smtp/src/modules/event-handlers/use-case/send-event-messages.use-case.ts
> [SMTP] Log template size

- .changeset/mean-apricots-glow.md
- apps/avatax/vercel.json
> avatax reduce vercel memory limits

- .changeset/pretty-beers-agree.md
- apps/avatax/vercel.json
> Increase memory in Avatax

- .changeset/red-hounds-crash.md
- apps/smtp/src/modules/smtp/services/smtp-email-sender.ts
> [SMTP] Log timeout error

- .cspell.json
- apps/cms-v2/src/modules/channel-provider-connection/channel-provider-connection.router.ts
- apps/klaviyo/src/lib/klaviyo.ts
- apps/klaviyo/src/pages/api/configuration.ts
- apps/products-feed/src/modules/app-configuration/app-configuration.router.ts
- apps/products-feed/src/modules/category-mapping/category-mapping.router.ts
- apps/search/src/pages/api/setup-indices.ts
Configured cspell checker to check logger calls for typos
> Add cspell to logger calls

- package.json
Update PNPM to the newest version. No lockfile changes
> Update PNPM to 9.12.3

- .github/labeler.yml
- .github/workflows/labeler.yml
- .github/workflows/prepare-release.yml
Updated GHA actions based on [actionlint](https://github.com/rhysd/actionlint)
Labeler config updated via https://github.com/actions/labeler#create-workflow
> Update GHA actions based on actionlint

- .changeset/six-lamps-shop.md
- apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-adapter.ts
- apps/avatax/src/pages/api/webhooks/checkout-calculate-taxes.ts
> log suspicious taxes calculation

- apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-adapter.ts
> improve log for non zero line

- .changeset/chilly-doors-film.md
- .changeset/fair-cooks-invite.md
- .changeset/four-seahorses-itch.md
- .changeset/loud-trains-glow.md
- .changeset/real-shrimps-hunt.md
- .changeset/sharp-mirrors-talk.md
- .changeset/silver-mangos-behave.md
- .changeset/thick-pumas-perform.md
- .changeset/thirty-monkeys-behave.md
Remove Segment release notes - when Segment is ready it will have one release note
> Cleanup Segment release notes

- .changeset/angry-zebras-collect.md
- apps/avatax/package.json
- apps/avatax/src/pages/api/register.ts
- apps/cms-v2/package.json
- apps/cms-v2/src/pages/api/register.ts
- apps/klaviyo/package.json
- apps/klaviyo/src/pages/api/register.ts
- apps/products-feed/package.json
- apps/products-feed/src/pages/api/register.ts
- apps/search/package.json
- apps/search/src/pages/api/register.ts
- apps/segment/package.json
- apps/segment/src/pages/api/register.ts
- apps/smtp/package.json
- apps/smtp/src/pages/api/register.ts
- pnpm-lock.yaml
Removed regex escape for `ALLOWED_DOMAINS_URL` env variable from register handler. It isn't user input and escaping regex was causing problem with apps installation.
> Fix /register issue with `ALLOWED_DOMAIN_URL` env variable

- .changeset/purple-shirts-listen.md
- apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-adapter.test.ts
- apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-adapter.ts
- apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-response-lines-transformer.ts
> extra logs for lines + tests

- .github/workflows/e2e.yml
> Fix e2e: add missing env vars

- CODEOWNERS
> Change CODEOWNERS to extensibility-team

- .github/workflows/main.yml
> Run workflow on push to main

- codecov.yml
Set CodeCov to be in informational mode: https://docs.codecov.com/docs/commit-status#informational
> Update CodeCov to be informational

- .changeset/many-taxis-film.md
- .changeset/witty-islands-listen.md
- apps/avatax/vercel.json
- apps/cms-v2/vercel.json
- apps/products-feed/vercel.json
- apps/search/vercel.json
- apps/segment/vercel.json
- apps/smtp/vercel.json
> allow functions multi region

- .changeset/warm-meals-roll.md
- apps/segment/src/pages/api/trpc/[trpc].ts
> Fix tRPC wrapping in Segment app

- .changeset/silly-months-clean.md
> Update Segment changeset with proper memory value

- .devcontainer/avatax/devcontainer.json
- .devcontainer/avatax/docker-compose.yml
> Rename devcontainer docker compose & add recommended vs code extensions

- packages/eslint-config-saleor/index.js
> add max-params rule to eslint

- .github/workflows/e2e.yml
> Update 1password vault for GHA

- apps/avatax/.env.example
- apps/cms/.env.example
- apps/klaviyo/.env.example
- apps/products-feed/.env.example
- apps/search/.env.example
- apps/segment/.env.example
- apps/smtp/.env.example
> update `.env.example` to contain ALLOWED_DOMAIN_URL described

- apps/avatax/.graphqlrc.ts
- apps/avatax/generated/graphql.ts
- apps/cms/.graphqlrc.yml
- apps/cms/generated/graphql.ts
- apps/klaviyo/.graphqlrc.yml
- apps/klaviyo/generated/graphql.ts
- apps/products-feed/.graphqlrc.yml
- apps/products-feed/generated/graphql.ts
- apps/search/.graphqlrc.yml
- apps/search/generated/graphql.ts
- apps/segment/.graphqlrc.ts
- apps/segment/generated/graphql.ts
- apps/smtp/.graphqlrc.yml
- apps/smtp/generated/graphql.ts
hooks generated were not used - only server side calls
> Remove urql hooks from codegen

- apps/avatax/.env.example
- apps/avatax/src/env.ts
- apps/avatax/src/instrumentation.ts
- apps/avatax/src/instrumentations/otel-node.ts
- apps/cms/.env.example
- apps/cms/src/instrumentation.ts
- apps/cms/src/instrumentations/otel-node.ts
- apps/klaviyo/.env.example
- apps/klaviyo/src/instrumentation.ts
- apps/klaviyo/src/instrumentations/otel-node.ts
- apps/products-feed/.env.example
- apps/products-feed/src/instrumentation.ts
- apps/products-feed/src/instrumentations/otel-node.ts
- apps/search/.env.example
- apps/search/src/instrumentation.ts
- apps/search/src/instrumentations/otel-node.ts
- apps/segment/.env.example
- apps/segment/src/env.ts
- apps/segment/src/instrumentation.ts
- apps/segment/src/instrumentations/otel-node.ts
- apps/smtp/.env.example
- apps/smtp/src/instrumentation.ts
- apps/smtp/src/instrumentations/otel-node.ts
- packages/otel/src/batch-span-processor-factory.ts
> Disable OTEL setup for egde runtime

- apps/avatax/package.json
- apps/cms/package.json
- apps/klaviyo/package.json
- apps/products-feed/package.json
- apps/search/package.json
- apps/segment/package.json
- apps/smtp/package.json
- package.json
- packages/e2e/package.json
- packages/eslint-config-saleor/package.json
- packages/logger/package.json
- packages/otel/package.json
- packages/react-hook-form-macaw/package.json
- packages/sentry-utils/package.json
- packages/shared/package.json
- packages/trpc/package.json
- packages/ui/package.json
- packages/webhook-utils/package.json
- pnpm-lock.yaml
* https://www.npmjs.com/package/sort-package-json
> Sort package.json keys with sort-package-json

- .github/workflows/e2e.yml
After this change e2e will be run on:
* 3.19
* 3.20
* latest version
> Run e2e on latest version

- .changeset/witty-fishes-tell.md
- apps/avatax/src/instrumentations/otel-node.ts
- apps/avatax/src/lib/app-internal-tracer.ts
- apps/avatax/src/lib/app-root-tracer.ts
- apps/avatax/src/lib/create-instrumented-graphql-client.ts
- apps/avatax/src/modules/avatax/avatax-client.ts
- apps/avatax/src/modules/calculate-taxes/use-case/calculate-taxes.use-case.test.ts
- apps/avatax/src/modules/calculate-taxes/use-case/calculate-taxes.use-case.ts
- apps/avatax/src/modules/client-logs/calculate-taxes-log-request.ts
- apps/avatax/src/modules/client-logs/order-cancelled-log-request.ts
- apps/avatax/src/modules/client-logs/order-confirmed-log-request.ts
- apps/avatax/src/pages/api/webhooks/checkout-calculate-taxes.ts
- apps/avatax/src/pages/api/webhooks/order-calculate-taxes.ts
- apps/avatax/src/pages/api/webhooks/order-cancelled.ts
- apps/avatax/src/pages/api/webhooks/order-confirmed.ts
* Added custom spans for Saleor webhook handlers
* Added custom spans for AvaTax API calls
* Refactored & improved client logs
> Add custom spans to AvaTax app

- .cspell.json
- .devcontainer/avatax/Dockerfile
- .devcontainer/cms/Dockerfile
- .devcontainer/klaviyo/Dockerfile
- .devcontainer/products-feed/Dockerfile
- .devcontainer/search/Dockerfile
- .devcontainer/segment/Dockerfile
- .devcontainer/smtp/Dockerfile
- README.md
- package.json
> Update PNPM to 10.6.3

- .changeset/lucky-years-develop.md
> Fix broken changeset

- .changeset/famous-owls-pull.md
- packages/otel/src/observability-attributes.ts
> Fix wrong observability attribute key name

- packages/e2e/.eslintrc.cjs
- packages/logger/.eslintrc.cjs
- packages/otel/.eslintrc.cjs
- packages/react-hook-form-macaw/.eslintrc.cjs
- packages/sentry-utils/.eslintrc.cjs
- packages/shared/.eslintrc.cjs
- packages/shared/src/metadata-manager.ts
- packages/trpc/.eslintrc.cjs
- packages/trpc/src/http-batch-link.ts
- packages/ui/.eslintrc.cjs
- packages/ui/src/text-link.tsx
- packages/webhook-utils/.eslintrc.cjs
> Fix lint issues for `packages/*`

- .changeset/twelve-planets-relate.md
- apps/avatax/src/app/api/trpc/[trpc]/route.ts
> Export tRPC handler once in app route

- .husky/pre-commit
> Update pre-commit to use pnpm

- apps/avatax/eslint.config.js
- apps/avatax/src/modules/avatax/avatax-client-tax-code.service.test.ts
- apps/avatax/src/modules/avatax/order-confirmed/saleor-order-to-avatax-lines-transformer.test.ts
- apps/cms/eslint.config.js
- apps/klaviyo/eslint.config.js
- apps/products-feed/eslint.config.js
- apps/products-feed/src/modules/app-configuration/attribute-fetcher.ts
- apps/products-feed/src/modules/category-mapping/categories-fetcher.ts
- apps/products-feed/src/modules/google-feed/fetch-product-data.test.ts
- apps/search/eslint.config.js
- apps/segment/eslint.config.js
- apps/segment/src/modules/configuration/dynamo-app-config-manager.test.ts
- apps/smtp/eslint.config.js
- apps/smtp/src/modules/smtp/configuration/smtp-configuration.service.test.ts
- apps/smtp/src/modules/smtp/services/email-compiler.test.ts
- packages/eslint-config/index.js
- packages/eslint-config/lint-staged.config.js
- packages/eslint-config/package.json
- packages/logger/eslint.config.js
- packages/otel/eslint.config.js
- packages/react-hook-form-macaw/src/components/Combobox.tsx
- packages/shared/eslint.config.js
- packages/shared/src/saleor-version-compatibility-validator.test.ts
- packages/trpc/src/context.ts
- packages/ui/eslint.config.js
- pnpm-lock.yaml
Enable recommended rules globally and make them `warn` for specific app/package
> Enable recommended eslint rules

- apps/avatax/src/env.ts
> Fix `NODE_ENV` variable typing in AvaTax

- apps/stripe/src/modules/stripe/stripe-payment-intents-api.test.ts
- apps/stripe/src/modules/stripe/stripe-publishable-key.test.ts
- apps/stripe/src/modules/stripe/stripe-publishable-key.ts
- apps/stripe/src/modules/stripe/stripe-restricted-key.test.ts
- apps/stripe/src/modules/stripe/stripe-restricted-key.ts
> Refactor Stripe key handling: improve validation and add tests for publishable and restricted keys

- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
> Fix typo in charge request

- apps/stripe/src/__tests__/mocks/app-config-repo.ts
- apps/stripe/src/__tests__/mocks/constants.ts
- apps/stripe/src/app/api/stripe/webhook/use-case.ts
- apps/stripe/src/app/api/stripe/webhook/webhook-params.test.ts
- apps/stripe/src/app/api/stripe/webhook/webhook-params.ts
- apps/stripe/src/lib/random-id.test.ts
- apps/stripe/src/lib/random-id.ts
- apps/stripe/src/modules/app-config/app-config-repo.ts
- apps/stripe/src/modules/app-config/file-app-config-repo.test.ts
- apps/stripe/src/modules/app-config/file-app-config-repo.ts
> Use config id instead channel id in stripe webhook

- apps/stripe/src/app/api/saleor/payment-gateway-initialize-session/use-case-response.test.ts
- apps/stripe/src/app/api/saleor/payment-gateway-initialize-session/use-case-response.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case-response.test.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case-response.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case.test.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case.ts
- apps/stripe/src/modules/saleor/saleor-webhook-responses.test.ts
- apps/stripe/src/modules/saleor/saleor-webhook-responses.ts
- apps/stripe/src/modules/stripe/stripe-client-secret.test.ts
- apps/stripe/src/modules/stripe/stripe-payment-intent-id.test.ts
> Refactor response tests and types for improved clarity and consistency

- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case-response.test.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case-response.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
> Fix Stripe app Saleor Charge Failure / Charge Action Required API response

- apps/stripe/src/__tests__/mocks/transaction-initalize-session-event.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/event-data-parser.test.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/event-data-parser.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case-response.test.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case-response.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case.test.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case.ts
> Fix Stripe API request params

- apps/stripe/src/app/api/saleor/transaction-initialize-session/event-data-parser.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case-response.test.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case-response.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case.test.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case.ts
- apps/stripe/src/modules/stripe/stripe-payment-intent-api-error.test.ts
- apps/stripe/src/modules/stripe/stripe-payment-intent-api-error.ts
- apps/stripe/src/modules/stripe/stripe-payment-intents-api.ts
- apps/stripe/src/modules/stripe/types.ts
> Error handling for Stripe API

- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case.test.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case.ts
- apps/stripe/src/modules/stripe/payment-methods/card.test.ts
- apps/stripe/src/modules/stripe/payment-methods/card.ts
- apps/stripe/src/modules/stripe/payment-methods/types.ts
> Add better support for authorization flow

- .prettierignore
- apps/avatax/.prettierignore
- apps/avatax/lint-staged.config.js
- apps/cms/.prettierignore
- apps/cms/lint-staged.config.js
- apps/klaviyo/.prettierignore
- apps/klaviyo/lint-staged.config.js
- apps/products-feed/.prettierignore
- apps/products-feed/lint-staged.config.js
- apps/search/.prettierignore
- apps/search/lint-staged.config.js
- apps/segment/.prettierignore
- apps/segment/lint-staged.config.js
- apps/smtp/.prettierignore
- apps/smtp/lint-staged.config.js
- apps/stripe/.prettierignore
- apps/stripe/lint-staged.config.js
- lint-staged.config.js
- packages/react-hook-form-macaw/lint-staged.config.js
- packages/sentry-utils/lint-staged.config.js
- packages/shared/lint-staged.config.js
- packages/trpc/lint-staged.config.js
- packages/ui/lint-staged.config.js
- packages/webhook-utils/.prettierignore
Prettier doesn't work well with monorepo https://github.com/prettier/prettier/issues/4081 hence we have to have `.prettierignore` per app/package
> Fix prettier / lint-staged

- apps/stripe/src/__tests__/mocks/stripe-events/mocked-payment-intent-amount-capturable-updated.ts
- apps/stripe/src/app/api/stripe/webhook/stripe-event-handlers/payment-intent-amount-capturable-updated-handler.test.ts
- apps/stripe/src/app/api/stripe/webhook/stripe-event-handlers/payment-intent-amount-capturable-updated-handler.ts
- apps/stripe/src/app/api/stripe/webhook/stripe-event-handlers/payment-intent-succeeded-handler.test.ts
- apps/stripe/src/app/api/stripe/webhook/stripe-event-handlers/payment-intent-succeeded-handler.ts
- apps/stripe/src/app/api/stripe/webhook/use-case.test.ts
- apps/stripe/src/app/api/stripe/webhook/use-case.ts
- apps/stripe/src/modules/transaction-result/map-payment-intent-status-to-transaction-result.test.ts
- apps/stripe/src/modules/transaction-result/map-payment-intent-status-to-transaction-result.ts
> Add new event for Stripe webhook - `amount_capturable_updated`

- apps/stripe/generated/graphql.ts
- apps/stripe/graphql/fragments/event-metadata.graphql
- apps/stripe/src/app/api/manifest/route.integration.test.ts
- apps/stripe/src/app/api/saleor/payment-gateway-initialize-session/route.ts
- apps/stripe/src/app/api/saleor/transaction-charge-requested/route.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/route.ts
- apps/stripe/src/app/api/saleor/transaction-process-session/route.ts
- apps/stripe/src/app/api/saleor/with-recipient-verification.test.ts
- apps/stripe/src/app/api/saleor/with-recipient-verification.ts
> saleor webhooks recipient verification

- apps/stripe/src/__tests__/mocks/mocked-recorded-transaction.ts
- apps/stripe/src/__tests__/mocks/mocked-stripe-payment-intent-id.ts
- apps/stripe/src/app/api/saleor/transaction-charge-requested/use-case.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case-response.test.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case.ts
- apps/stripe/src/app/api/saleor/transaction-process-session/use-case.ts
- apps/stripe/src/app/api/stripe/webhook/use-case-success.test.ts
- apps/stripe/src/app/api/stripe/webhook/use-case.ts
- apps/stripe/src/modules/resolved-transaction-flow.ts
- apps/stripe/src/modules/stripe/payment-methods/card.ts
- apps/stripe/src/modules/stripe/payment-methods/types.ts
- apps/stripe/src/modules/stripe/stripe-payment-intent-id.test.ts
- apps/stripe/src/modules/stripe/stripe-payment-intent-id.ts
- apps/stripe/src/modules/transaction-result/map-payment-intent-status-to-transaction-result.ts
- apps/stripe/src/modules/transactions-recording/domain/recorded-transaction.ts
- apps/stripe/src/modules/transactions-recording/repositories/dynamodb/dynamodb-transaction-recorder-repo.ts
> Make creation of Stripe PI throwable

- apps/stripe/src/__tests__/mocks/mocked-stripe-payment-intents-api.ts
- apps/stripe/src/app/api/saleor/transaction-charge-requested/use-case.test.ts
- apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case.test.ts
- apps/stripe/src/app/api/saleor/transaction-process-session/use-case.test.ts
> Extract mockedStripePaymentIntentsApi

- apps/stripe/src/app/api/saleor/transaction-charge-requested/use-case-response.ts
- apps/stripe/src/app/api/saleor/transaction-process-session/use-case-response.ts
- apps/stripe/src/app/api/stripe/webhook/transaction-event-report-variables-resolver.ts
- apps/stripe/src/modules/saleor/transaction-event-reporter.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
> Update app sdk to fix issue with typing actions for transactions events

- apps/stripe/src/app/api/stripe/webhook/route.ts
> add saleorApiUrl to stripe webhook span

- apps/stripe/src/app/api/stripe/webhook/use-case.ts
> log about missing config

- apps/stripe/src/app/api/webhooks/saleor/payment-gateway-initialize-session/route.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-cancelation-requested/route.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-cancelation-requested/webhook-definition.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-charge-requested/route.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-charge-requested/webhook-definition.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-initialize-session/route.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-initialize-session/use-case.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-process-session/route.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-process-session/use-case.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-refund-requested/route.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-refund-requested/webhook-definition.ts
- apps/stripe/src/app/api/webhooks/stripe/route.ts
- apps/stripe/src/app/api/webhooks/stripe/use-case.ts
- apps/stripe/src/lib/env.ts
- apps/stripe/src/lib/tracing.ts
- apps/stripe/src/modules/transactions-recording/repositories/dynamodb/dynamodb-transaction-recorder-repo.ts
- packages/otel/src/observability-attributes.ts
> Rework logs

- apps/stripe/src/modules/ui/stripe-configs/empty-configs.tsx
- apps/stripe/src/pages/config/new.tsx
> Small fixes to Stripe UI

- apps/stripe/src/modules/stripe/stripe-api-version.ts
- apps/stripe/src/modules/stripe/stripe-client.ts
- apps/stripe/src/modules/stripe/stripe-webhook-manager.test.ts
- apps/stripe/src/modules/stripe/stripe-webhook-manager.ts
> Freeze Stripe API version to the latest available

- .cursor/mcp.json
- .gitignore
- .vscode/mcp.json
- README.md
- mcp/.env.example
- mcp/start-mcp-graphql.sh
> MCP support

- apps/stripe/src/app/api/webhooks/saleor/transaction-initialize-session/event-data-parser.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-initialize-session/payment-method-resolver.ts
- apps/stripe/src/modules/stripe/payment-methods/apple-pay.test.ts
- apps/stripe/src/modules/stripe/payment-methods/apple-pay.ts
> Add Apple pay support to Stripe app

- apps/stripe/src/app/api/webhooks/saleor/transaction-initialize-session/event-data-parser.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-initialize-session/payment-method-resolver.ts
- apps/stripe/src/modules/stripe/payment-methods/apple-pay.ts
- apps/stripe/src/modules/stripe/payment-methods/paypal.test.ts
- apps/stripe/src/modules/stripe/payment-methods/paypal.ts
- cspell.config.js
> Add PayPal support

- apps/stripe/src/modules/ui/app-header.tsx
- apps/stripe/src/modules/ui/channel-configs/channel-config-mapping-section.tsx
- apps/stripe/src/modules/ui/stripe-configs/channel-config-section.tsx
- apps/stripe/src/modules/ui/stripe-configs/delete-configuration-modal-content.tsx
- apps/stripe/src/modules/ui/stripe-configs/empty-configs.tsx
- apps/stripe/src/modules/ui/stripe-configs/new-stripe-config-form.tsx
- apps/stripe/src/modules/ui/stripe-configs/stripe-configs-list.tsx
- apps/stripe/src/pages/config/index.tsx
- apps/stripe/src/pages/config/new.tsx
> Improve Stripe app UI

- apps/stripe/src/app/api/webhooks/saleor/transaction-initialize-session/use-case.test.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-initialize-session/use-case.ts
- apps/stripe/src/modules/stripe/stripe-payment-intents-api.test.ts
- apps/stripe/src/modules/stripe/stripe-payment-intents-api.ts
- apps/stripe/src/modules/stripe/types.ts
> send metadata to stripe

- apps/stripe/eslint.config.js
- apps/stripe/src/__tests__/integration/dynamodb/create-table.ts
- apps/stripe/src/__tests__/integration/dynamodb/delete-table.ts
- apps/stripe/src/__tests__/integration/dynamodb/global-setup.integration-dynamo.ts
- apps/stripe/src/__tests__/integration/dynamodb/setup.integration-dynamo.ts
- apps/stripe/src/__tests__/setup.units.ts
- packages/eslint-config/index.js
> Loosen eslint for tests

- .changeset/ninety-pianos-shave.md
- apps/stripe/src/modules/app-config/trpc-handlers/new-stripe-config-input-schema.test.ts
- apps/stripe/src/modules/app-config/trpc-handlers/new-stripe-config-input-schema.ts
- apps/stripe/src/modules/stripe/stripe-payment-intent-id.test.ts
- apps/stripe/src/modules/stripe/stripe-payment-intent-id.ts
- apps/stripe/src/modules/stripe/stripe-publishable-key.test.ts
- apps/stripe/src/modules/stripe/stripe-publishable-key.ts
- apps/stripe/src/modules/stripe/stripe-refund-id.ts
- apps/stripe/src/modules/stripe/stripe-restricted-key.test.ts
- apps/stripe/src/modules/stripe/stripe-restricted-key.ts
- apps/stripe/src/modules/stripe/stripe-webhook-secret.test.ts
- apps/stripe/src/modules/stripe/stripe-webhook-secret.ts
- apps/stripe/src/pages/config/new.tsx
- cspell.config.js
> Dont throw if stripe ids format is unexpected

- README.md
> Update apps readme with new link to Stripe

- .changeset/fast-owls-decide.md
- apps/stripe/src/modules/app-config/repositories/dynamodb/dynamodb-app-config-repo.ts
> Wrap DynamoDB building command in try/catch for improved error handling

- .changeset/spotty-zebras-agree.md
- apps/stripe/src/modules/app-config/trpc-handlers/new-stripe-config-input-schema.test.ts
- apps/stripe/src/modules/app-config/trpc-handlers/new-stripe-config-input-schema.ts
> fix validation when creating conifg

- .changeset/red-donkeys-remain.md
- apps/stripe/src/app/api/webhooks/saleor/payment-gateway-initialize-session/route.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-cancelation-requested/route.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-charge-requested/route.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-initialize-session/route.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-process-session/route.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-refund-requested/route.ts
- apps/stripe/src/app/api/webhooks/stripe/route.ts
- apps/stripe/src/lib/observability-saleor-api-url.ts
- apps/stripe/src/lib/observability-source-object-id.ts
> Add observability attributes for Sentry / logs

- adr/0002-use-zod-branded-types.md
> Add Zod branded types ADR

- .github/workflows/e2e.yml
- .github/workflows/run-e2e-cron.yml
- .github/workflows/run-e2e-dispatch.yml
- .github/workflows/run-e2e-label.yml
> Fix e2e reusable workflow

- apps/stripe/src/__tests__/integration/webhooks/fixtures/transaction-charge-requested-fixture.ts
- apps/stripe/src/__tests__/integration/webhooks/payment-gateway-initialize.test.ts
- apps/stripe/src/__tests__/integration/webhooks/transaction-cancelation-requested.test.ts
- apps/stripe/src/__tests__/integration/webhooks/transaction-charge-requested.test.ts
- apps/stripe/src/__tests__/integration/webhooks/transaction-initialize-session.test.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-charge-requested/webhook-definition.ts
- apps/stripe/src/modules/stripe/types.ts
> Add integration test for charge requested

- .changeset/forty-spies-vanish.md
- apps/stripe/src/modules/app-config/trpc-handlers/new-stripe-config-input-schema.test.ts
- apps/stripe/src/modules/app-config/trpc-handlers/new-stripe-config-input-schema.ts
> Fix Stripe validation

- apps/stripe/src/__tests__/integration/webhooks/fixtures/transaction-refund-requested-fixture.ts
- apps/stripe/src/__tests__/integration/webhooks/transaction-refund-requested.test.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-charge-requested/route.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-initialize-session/route.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-refund-requested/route.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-refund-requested/webhook-definition.ts
> [Stripe] Add integration test for refund requested route

- .github/workflows/main.yml
- apps/stripe/package.json
- codecov.yml
> Enable codecov reporting

- .github/workflows/assign-pr.yml
> Fix assign PR workflow

- apps/np-atobarai/package.json
- apps/np-atobarai/src/__tests__/mocks/app-config/mocked-app-config-repo.ts
- apps/np-atobarai/src/__tests__/mocks/app-config/mocked-app-config.ts
- apps/np-atobarai/src/app/api/webhooks/saleor/payment-gateway-initialize-session/route.ts
- apps/np-atobarai/src/app/api/webhooks/saleor/payment-gateway-initialize-session/use-case.test.ts
- apps/np-atobarai/src/app/api/webhooks/saleor/payment-gateway-initialize-session/use-case.ts
- apps/np-atobarai/src/lib/errors.ts
- apps/np-atobarai/src/modules/app-config/app-config.test.ts
- apps/np-atobarai/src/modules/app-config/app-config.ts
- apps/np-atobarai/src/modules/app-config/types.ts
- pnpm-lock.yaml
> Create app config model

- apps/np-atobarai/package.json
- apps/np-atobarai/src/__tests__/setup.ts
- apps/np-atobarai/src/lib/env.ts
- apps/np-atobarai/src/lib/saleor-app.ts
- apps/np-atobarai/src/modules/dynamodb/dynamodb-client.ts
- apps/np-atobarai/src/modules/dynamodb/dynamodb-main-table.ts
- apps/np-atobarai/turbo.json
- pnpm-lock.yaml
> dynamodb setup and apl

- .github/copilot-instructions.md
- apps/np-atobarai/src/app/api/webhooks/saleor/base-use-case.test.ts
- apps/np-atobarai/src/app/api/webhooks/saleor/base-use-case.ts
- apps/np-atobarai/src/app/api/webhooks/saleor/fulfillment-tracking-number-updated/use-case.ts
- apps/np-atobarai/src/app/api/webhooks/saleor/payment-gateway-initialize-session/use-case.ts
- apps/np-atobarai/src/app/api/webhooks/saleor/transaction-initialize-session/use-case.ts
- apps/np-atobarai/src/app/api/webhooks/saleor/transaction-process-session/use-case.ts
> Add BaseUseCase to NP Atobarai / copilot instructions

- pnpm-lock.yaml
- pnpm-workspace.yaml
> Force update form-data@3.0.1 to 3.0.4

- apps/stripe/src/app/api/webhooks/stripe/stripe-webhook-responses.ts
- apps/stripe/src/app/api/webhooks/stripe/use-case-success.test.ts
- apps/stripe/src/app/api/webhooks/stripe/use-case.ts
> improve messages for stripe handling events outside of app

- .changeset/curvy-melons-tie.md
- apps/stripe/src/app/api/webhooks/saleor/transaction-initialize-session/event-data-parser.ts
- apps/stripe/src/app/api/webhooks/saleor/transaction-initialize-session/use-case.ts
> improve invalid data log for Stripe payment method
