apps/cms/graphql/fragments/WebhookProduct.graphql
apps/cms/src/pages/api/manifest.ts
apps/cms/src/pages/api/webhooks/product-updated.ts

This introduces product data updates to all product variant items in all CMS provider instances, triggered on Saleor product updates webhook events.
Before this changes, product CMS items fields could not be updated once product was updated in the Saleor (case when only product was updated in Saleor Dashboard without altering variants). Products fields that are now updating on every product update: `product_id`, `product_slug`, `product_name`.
That way, it fixes https://github.com/saleor/apps/issues/317.
https://user-images.githubusercontent.com/9825562/227214378-1df98df6-6f5f-443b-9f03-51edccf5e0a3.mp4

Product data updates in CMS product variant objects

---

.changeset/nice-donkeys-stare.md
apps/cms/package.json
apps/cms/src/modules/channels/ui/channel-configuration-form.tsx
apps/cms/src/modules/provider-instances/ui/provider-icon.tsx
apps/cms/src/modules/provider-instances/ui/provider-instance-configuration-form.tsx
apps/cms/src/modules/provider-instances/ui/provider-instance-configuration.tsx
apps/cms/src/modules/provider-instances/ui/provider-instances-list.tsx
apps/cms/src/modules/provider-instances/ui/provider-instances.tsx
pnpm-lock.yaml

It fixes regression in provider configuration UI introduced in https://github.com/saleor/apps/pull/349.
Fixes https://github.com/saleor/apps/issues/373.
Also additionally, this PR introduce:
- logo to distinct provider configuration instance in selector of providers configuration view (they can have the same name, e.g. "Prod" for Strapi, "Prod" for Contentful, "Prod" for DatoCMS, etc.)
- configuration id displayed in disabled field of configuration instance form, just for information/debugging purpose
The effect:

Provider configurations UI fixes

---

.changeset/old-dingos-hide.md
apps/cms/package.json
apps/cms/src/lib/cms/client/clients-execution.ts
apps/cms/src/lib/cms/config/providers.ts
apps/cms/src/lib/cms/providers/contentful.ts
apps/cms/src/lib/cms/providers/datocms.ts
apps/cms/src/lib/cms/providers/strapi.ts
apps/cms/src/lib/cms/types.ts
apps/cms/src/modules/channels/ui/channels.tsx
apps/cms/src/modules/cms/hooks/useProductsVariantsSync.ts
apps/cms/src/modules/provider-instances/ui/hooks/usePingProviderInstance.ts
apps/cms/src/modules/provider-instances/ui/provider-instance-configuration-form.tsx
apps/cms/src/modules/provider-instances/ui/provider-instance-configuration.tsx
apps/cms/src/modules/provider-instances/ui/provider-instance-ping.tsx
apps/cms/src/modules/provider-instances/ui/provider-instances.tsx
apps/cms/src/pages/api/ping-provider-instance.ts
apps/cms/src/pages/api/sync-products-variants.ts
apps/cms/src/pages/api/webhooks/_utils.ts
apps/cms/src/pages/api/webhooks/product-updated.ts
apps/cms/src/pages/api/webhooks/product-variant-updated.ts
pnpm-lock.yaml

Fixes for https://github.com/saleor/apps/issues/314
plus:
- error notifications on sync issues
- checking connection status of configuration instance, closes https://github.com/saleor/apps/issues/242
- skipping update webhooks processing if issuing principal is this same CMS app (app bulk product sync was causing triggering unnecessary product and variant webhook events, due to updating metadata with ID from CMS provider, where product variant data was uploaded/removed from). Related https://github.com/saleor/saleor/issues/12538.

Fix CMS app issues

---

.changeset/dull-planets-dance.md
apps/taxes/src/modules/app/webhook-response.ts
apps/taxes/src/modules/ui/country-select/country-select.tsx
apps/taxes/src/pages/api/webhooks/order-calculate-taxes.ts

After introducing the `WebhookResponse` class, we had a regression with the calculated taxes not showing in the Dashboard. It was caused by omitting the usage of `ctx.buildResponse` function for a sync webhook.
Besides the fix, the PR includes a small improvement to `CountrySelect` and a comment with an idea for future improvement (which would detect this issue).

fix: tax not calculating

---

apps/crm/package.json
apps/crm/src/lib/metadata-manager.ts
apps/crm/src/modules/mailchimp/mailchimp-config-settings-manager.ts
apps/crm/src/pages/api/webhooks/customer-created.ts
apps/crm/src/test/webhooks/customer-created-webhook.test.ts
pnpm-lock.yaml

This is POC of public-level API test. 
The assumption is to write tests on "entrypoints" - webhook handlers, API handlers and pages/screens
I believe solid layer of such tests with mocks that cover various scenarios are important to cover business domain. E2E layer on top can be thin.
This test technically can use msw/polly to record real responses, but I failed to set it up (I tried MSW) - I need another attempt, but maybe polly is better
This test mocks:
- webhook payload from Saleor
- app metadata set in Saleor (app config)
and asserts if Mailchimp client properly received fields (I assume testing HTTP here is testing library internals)

Add test for CUSTOMER_CREATED webhook in CRM app

---

apps/products-feed/next.config.js
apps/products-feed/package.json
apps/products-feed/src/lib/google-feed/fetch-product-data.ts
apps/products-feed/src/lib/google-feed/get-google-feed-settings.ts
apps/products-feed/src/lib/metadata-manager.ts
apps/products-feed/src/modules/app-configuration/app-config-container.ts
apps/products-feed/src/modules/app-configuration/app-config-input-schema.ts
apps/products-feed/src/modules/app-configuration/app-config.ts
apps/products-feed/src/modules/app-configuration/app-configuration.router.ts
apps/products-feed/src/modules/app-configuration/get-app-configuration.service.ts
apps/products-feed/src/modules/app-configuration/ui/channels-configuration.tsx
apps/products-feed/src/modules/app-configuration/ui/s3-configuration-form.tsx
apps/products-feed/src/modules/file-storage/s3/const.ts
apps/products-feed/src/modules/file-storage/s3/create-s3-client-from-configuration.ts
apps/products-feed/src/modules/file-storage/s3/get-file-details.ts
apps/products-feed/src/modules/file-storage/s3/upload-file.ts
apps/products-feed/src/modules/file-storage/s3/upload-multi-part.ts
apps/products-feed/src/modules/file-storage/s3/upload-single-part.ts
apps/products-feed/src/modules/file-storage/s3/urls-and-names.ts
apps/products-feed/src/modules/metadata-cache/cache-configurator.ts
apps/products-feed/src/modules/metadata-cache/update-cache-for-configurations.ts
apps/products-feed/src/pages/api/feed/[url]/[channel]/google.xml.ts
pnpm-lock.yaml

- cursors are saved on the configuration update and saved in metadata
- feed generation uses the cached cursors for feed generation
- removed the feed endpoint side limit to handle bigger catalogs
- added support for s3
- if s3 is configured, use it to store the feed 
- if feed stored on s3 was generated lately, return it instead of generating each time

Cache query cursors for the product feed and support s3

---

apps/monitoring/backend/poetry.lock

Fixes CVE-2023-2650: Vulnerable OpenSSL included in cryptography wheels.

Upgrade cryptography to latest

---

apps/emails-and-messages/package.json
apps/emails-and-messages/scripts/migrations/README.md
apps/emails-and-messages/scripts/migrations/migration-utils.ts
apps/emails-and-messages/scripts/migrations/run-migration.ts
apps/emails-and-messages/scripts/migrations/run-report.ts
apps/emails-and-messages/src/modules/app-configuration/app-config-metadata-manager.ts
apps/emails-and-messages/src/modules/app-configuration/app-config-schema.ts
apps/emails-and-messages/src/modules/app-configuration/migrations/get-channels-assigned-to-config-id.test.ts
apps/emails-and-messages/src/modules/app-configuration/migrations/get-channels-assigned-to-config-id.ts
apps/emails-and-messages/src/modules/sendgrid/configuration/migrations/sendgrid-config-migration-v1-to-v2.ts
apps/emails-and-messages/src/modules/sendgrid/configuration/migrations/sendgrid-config-schema-v1.ts
apps/emails-and-messages/src/modules/sendgrid/configuration/migrations/sendgrid-config-schema-v2.ts
apps/emails-and-messages/src/modules/sendgrid/configuration/migrations/sendgrid-transform-v1-to-v2.test.ts
apps/emails-and-messages/src/modules/sendgrid/configuration/migrations/sendgrid-transform-v1-to-v2.ts
apps/emails-and-messages/src/modules/sendgrid/configuration/sendgrid-config-schema.ts
apps/emails-and-messages/src/modules/sendgrid/configuration/sendgrid-configuration.service.ts
apps/emails-and-messages/src/modules/sendgrid/configuration/sendgrid-metadata-manager-v1.ts
apps/emails-and-messages/src/modules/sendgrid/configuration/sendgrid-metadata-manager-v2.ts
apps/emails-and-messages/src/modules/sendgrid/configuration/sendgrid-metadata-manager.ts
apps/emails-and-messages/src/modules/smtp/configuration/migrations/mjml-config-schema-v1.ts
apps/emails-and-messages/src/modules/smtp/configuration/migrations/smtp-config-migration-v1-to-v2.ts
apps/emails-and-messages/src/modules/smtp/configuration/migrations/smtp-config-schema-v2.ts
apps/emails-and-messages/src/modules/smtp/configuration/migrations/smtp-transform-v1-to-v2.test.ts
apps/emails-and-messages/src/modules/smtp/configuration/migrations/smtp-transform-v1-to-v2.ts
apps/emails-and-messages/src/modules/smtp/configuration/mjml-metadata-manager.ts
apps/emails-and-messages/src/modules/smtp/configuration/smtp-config-schema.ts
apps/emails-and-messages/src/modules/smtp/configuration/smtp-metadata-manager-v2.ts
apps/emails-and-messages/src/modules/smtp/configuration/smtp-metadata-manager.ts
pnpm-lock.yaml

New version of the EAM app introduced breaking changes in the configuration schema:
- renamed `configurationName` to `name`
- `appConfiguration` has been removed (was used to map provider configuration to the channel)
- new `channels` field - gives us better flexibility how configuration should be used across the channels
How does the migration work:
- check if theres configuration set for the schema v2. If so, no migration is needed because it has been done already/was not needed
- if theres previous version, transform the data and return it
- if data are modified, save it in the new version
Notable mentions:
- No data is removed. Cleaning up after migration will be done after running a script (will be sent in a separate PR)
- The only place where the app is aware of any migrations is …

📧 Add runtime migrations to schema v2

---

.changeset/slimy-students-switch.md

The next release of the EAM app should be marked as minor, not major.
Since data migration was implemented, the upgrade is not breaking anymore.

📧 Downgrade EAM release to minor

---

.changeset/eighty-boxes-exist.md
apps/products-feed/src/modules/app-configuration/s3-configuration-form.tsx

Makes helper text more explicit. Change after QA feedback where it was mistaken with longer string. In S3 dashboard its something like the screen shot
Which doesn't work - should be only code.

Update helper text for PF app - S3->region field

---

.changeset/chilled-kiwis-type.md
apps/cms/src/pages/api/manifest.ts
apps/crm/src/pages/api/manifest.ts
apps/data-importer/src/pages/api/manifest.ts
apps/emails-and-messages/src/pages/api/manifest.ts
apps/invoices/src/pages/api/manifest.ts
apps/klaviyo/src/pages/api/manifest.ts
apps/products-feed/src/pages/api/manifest.ts
apps/search/src/pages/api/manifest.ts
apps/slack/src/pages/api/manifest.ts
apps/taxes/src/pages/api/manifest.ts

Apps never had "about" field in manifest filled - I pasted their description from Appstore now

Add about field in manifest of all apps. Sorted fields

---

.changeset/light-rocks-count.md
apps/taxes/graphql/subscriptions/OrderCreated.graphql
apps/taxes/graphql/subscriptions/OrderFulfilled.graphql
apps/taxes/src/modules/avatax/avatax-webhook.service.ts
apps/taxes/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-payload-lines-transformer.ts
apps/taxes/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-tax-code-matcher.test.ts
apps/taxes/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-tax-code-matcher.ts
apps/taxes/src/modules/avatax/order-created/avatax-order-created-adapter.ts
apps/taxes/src/modules/avatax/order-created/avatax-order-created-payload-lines-transformer.test.ts
apps/taxes/src/modules/avatax/order-created/avatax-order-created-payload-lines-transformer.ts
apps/taxes/src/modules/avatax/order-created/avatax-order-created-payload-transformer.test.ts
apps/taxes/src/modules/avatax/order-created/avatax-order-created-payload-transformer.ts
apps/taxes/src/modules/avatax/order-created/avatax-order-created-payload.service.ts
apps/taxes/src/modules/avatax/order-created/avatax-order-created-tax-code-matcher.test.ts
apps/taxes/src/modules/avatax/order-created/avatax-order-created-tax-code-matcher.ts
apps/taxes/src/modules/taxjar/calculate-taxes/taxjar-calculate-taxes-payload-lines-transformer.ts
apps/taxes/src/modules/taxjar/calculate-taxes/taxjar-calculate-taxes-tax-code-matcher.test.ts
apps/taxes/src/modules/taxjar/calculate-taxes/taxjar-calculate-taxes-tax-code-matcher.ts
apps/taxes/src/modules/taxjar/order-created/taxjar-order-created-adapter.ts
apps/taxes/src/modules/taxjar/order-created/taxjar-order-created-payload-lines-transformer.test.ts
apps/taxes/src/modules/taxjar/order-created/taxjar-order-created-payload-lines-transformer.ts
apps/taxes/src/modules/taxjar/order-created/taxjar-order-created-payload-transformer.test.ts
apps/taxes/src/modules/taxjar/order-created/taxjar-order-created-payload-transformer.ts
apps/taxes/src/modules/taxjar/order-created/taxjar-order-created-payload.service.ts
apps/taxes/src/modules/taxjar/order-created/taxjar-order-created-tax-code-matcher.test.ts
apps/taxes/src/modules/taxjar/order-created/taxjar-order-created-tax-code-matcher.ts
apps/taxes/src/modules/taxjar/taxjar-webhook.service.ts

During the initial implementation of the tax code matcher, I didn't add support for the `ORDER_CREATED` webhook. This is the scope of this PR.
The consequence is that the tax code match is not only used for tax calculation but is also sent along with the transaction details. It should result in displaying the line tax code in the provider dashboard.

feat: tax code create order

---

.github/dependabot.yaml

Current setup with limit: `0` is technically disabling dependabot.
Lets allow it to work *daily* but open only a single PR, so it doesn't bloat repository with dozens open PRs.
Once PR is merged, dependabot will continue checking

Allow dependabot to open a daily PR for every package, but limit to 1

---

.changeset/rare-spiders-argue.md
apps/emails-and-messages/src/components/box-footer.tsx
apps/emails-and-messages/src/modules/sendgrid/configuration/sendgrid-config-input-schema.test.ts
apps/emails-and-messages/src/modules/sendgrid/configuration/sendgrid-config-input-schema.ts
apps/emails-and-messages/src/modules/sendgrid/ui/sendgrid-events-section.tsx

An error message will be shown if the user tries to submit the form with an enabled event without the template.
Related: #686

📧 Prevent users from enabling events without the template

---

.changeset/healthy-bobcats-confess.md
apps/emails-and-messages/graphql/fragments/OrderDetails.graphql
apps/emails-and-messages/src/modules/event-handlers/default-payloads.ts
apps/emails-and-messages/src/modules/webhook-management/webhook-management-service.test.ts
apps/emails-and-messages/src/pages/api/webhooks/gift-card-sent.ts
apps/emails-and-messages/src/pages/api/webhooks/invoice-sent.ts

Add metadata and Private metadata to event payloads for feature parity with the customer emails plugin.
Related #313

Add metadata and privateMetadata to webhook payloads

---

.changeset/eleven-students-cheer.md
apps/cms/README.md
apps/cms/src/modules/ui/error-no-longer-maintained.tsx
apps/cms/src/pages/home.tsx
apps/cms/src/pages/index.tsx

CMS v1 app is deprecated and replaced with V2. This PR adds a frontend component that warns about it

cms v1 - notice about deprecation

---

.changeset/chatty-mugs-accept.md
apps/taxes/graphql/fragments/TaxBase.graphql
apps/taxes/graphql/subscriptions/OrderCreated.graphql
apps/taxes/src/mocks.ts
apps/taxes/src/modules/avatax/avatax-client.ts
apps/taxes/src/modules/avatax/avatax-entity-type-matcher.test.ts
apps/taxes/src/modules/avatax/avatax-entity-type-matcher.ts
apps/taxes/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-mock-generator.ts
apps/taxes/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-payload-transformer.test.ts
apps/taxes/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-payload-transformer.ts
apps/taxes/src/modules/avatax/order-created/avatax-order-created-payload-transformer.test.ts
apps/taxes/src/modules/avatax/order-created/avatax-order-created-payload-transformer.ts
apps/taxes/src/modules/channel-configuration/ui/channel-section.tsx
apps/taxes/src/modules/provider-connections/ui/providers-section.tsx
apps/taxes/src/modules/taxjar/calculate-taxes/taxjar-calculate-taxes-mock-generator.ts
apps/taxes/src/modules/taxjar/ui/taxjar-instructions.tsx

By providing the value for the Order metadata field of key `avataxEntityCode`, you can attach [`entityUseCode`](https://developer.avalara.com/erp-integration-guide/sales-tax-badge/designing/entity-code/) to transactions that will be created in Avatax. You can use this feature to, f.e., mark the customers that should be tax-exempted.
- added `metadata` to webhook orders
- added `AvataxEntityTypeMatcher` class that handles the entire logic of retrieving the entity code from metadata and validating it against Avatax API
- removed missed `<br />s` from instructions
https://github.com/saleor/appstore/issues/216

feat: taxes map entity type

---

.changeset/mean-ghosts-beam.md
apps/products-feed/src/modules/app-configuration/app-configuration.router.ts
apps/products-feed/src/modules/app-configuration/s3-configuration-form.tsx
apps/products-feed/src/modules/file-storage/s3/check-bucket-access.ts

- validate AWS credentials on save and prevent users from saving invalid configuration
- add button to test existing configurtion

EAM: Add AWS credentials validation

---

.changeset/ninety-lobsters-design.md
apps/taxes/graphql/subscriptions/OrderConfirmed.graphql
apps/taxes/src/modules/avatax/order-confirmed/avatax-order-confirmed-calculation-date-resolver.test.ts
apps/taxes/src/modules/avatax/order-confirmed/avatax-order-confirmed-calculation-date-resolver.ts
apps/taxes/src/modules/avatax/order-confirmed/avatax-order-confirmed-payload-transformer.ts

- Added support for reading the tax calculation date from metadata field `avataxTaxCalculationDate`. The value has to be valid UTC datetime string (e.g. "2021-08-31T13:00:00.000Z").

feat: Avatax metadata tax calculation date

---

.changeset/forty-shirts-battle.md
apps/taxes/graphql/subscriptions/OrderConfirmed.graphql
apps/taxes/src/modules/avatax/order-confirmed/avatax-order-confirmed-document-code-resolver.test.ts
apps/taxes/src/modules/avatax/order-confirmed/avatax-order-confirmed-document-code-resolver.ts
apps/taxes/src/modules/avatax/order-confirmed/avatax-order-confirmed-payload-transformer.ts

- Added support for reading document code from metadata field `avataxDocumentCode`. The default value is the order id from Saleor.

feat: Avatax metadata document code

---

.changeset/eight-oranges-appear.md
apps/search/graphql/fragments/OwnWebhook.graphql
apps/search/graphql/fragments/ProductData.graphql
apps/search/graphql/fragments/ProductVariantData.graphql
apps/search/graphql/mutations/CreateWebhook.graphql
apps/search/graphql/mutations/RemoveWebhook.graphql
apps/search/graphql/subscriptions/productVariantBackInStock.graphql
apps/search/graphql/subscriptions/productVariantOutOfStock.graphql
apps/search/src/components/ImportProductsToAlgolia.tsx
apps/search/src/components/MainInstructions.tsx
apps/search/src/components/WebhooksStatus.tsx
apps/search/src/components/WebhooksStatusInstructions.tsx
apps/search/src/domain/WebhookActivityToggler.service.ts
apps/search/src/lib/algolia/algoliaUtils.ts
apps/search/src/lib/algolia/is-configured.test.ts
apps/search/src/lib/algolia/is-configured.ts
apps/search/src/lib/algolia/is-webhook-update-needed.test.ts
apps/search/src/lib/algolia/is-webhook-update-needed.ts
apps/search/src/lib/getBaseUrl.ts
apps/search/src/lib/useWebhooksStatus.tsx
apps/search/src/lib/useWebhooksUpdate.tsx
apps/search/src/pages/api/manifest.ts
apps/search/src/pages/api/recreate-webhooks.ts
apps/search/src/pages/api/webhooks-status.ts
apps/search/src/pages/api/webhooks/saleor/product_variant_back_in_stock.ts
apps/search/src/pages/api/webhooks/saleor/product_variant_out_of_stock.ts
apps/search/webhooks.ts

Extended search model with two new fields:
- `inStock`: returns true if stock is available. To keep this up to date, the application subscribes to `ProductVariantOutOfStock` and `ProductVariantBackInStock` events
- `media`: array of objects containing URL and type of given file (video or image)
Users with existing app installations will be presented with UI allowing them to update the webhooks:

Search: Add media and stock flag

---

.changeset/silly-balloons-knock.md
.changeset/twelve-lamps-fry.md
apps/data-importer/package.json
apps/emails-and-messages/package.json
apps/invoices/package.json
apps/klaviyo/package.json
apps/products-feed/package.json
apps/search/package.json
apps/slack/package.json
apps/taxes/package.json
packages/shared/package.json
pnpm-lock.yaml

Clsx package was used when App was developed during the hackathon. Since we moved to a different UI package which makes it no longer needed.

Remove clsx package which is no longer used

---

.github/workflows/changeset-checker.yml

The action checks if PR has added a changeset. Check is skipped for the release branch.
PR without added changeset fails:
After adding the changeset:
Adding `skip changesets` label will turn the check off.

Add mandatory check for the changeset

---

.github/workflows/assign-pr.yml

This PR replaces the use of `assign-pr-creator-action` with the GitHub CLI.

Replace `assign-pr-creator-action` with GitHub CLI

---

.changeset/modern-apricots-hammer.md
apps/taxes/.env.example
apps/taxes/.eslintrc
apps/taxes/.gitignore
apps/taxes/next.config.js
apps/taxes/package.json
apps/taxes/sentry.client.config.ts
apps/taxes/sentry.edge.config.ts
apps/taxes/sentry.server.config.ts
apps/taxes/src/deploy.ts
apps/taxes/src/error.ts
apps/taxes/src/modules/app/webhook-response.ts
apps/taxes/src/modules/taxes/tax-error.ts
apps/taxes/src/modules/trpc/sentry-middleware.ts
apps/taxes/src/pages/configuration.tsx
apps/taxes/src/release-utils.ts
apps/taxes/src/sentry-utils.ts
apps/taxes/turbo.json
pnpm-lock.yaml

**Features**:
- copied the Sentry config from the Adyen App
- added new dependency: `@next/env`
- added new env vars
**Next steps**:
- move `release-utils` to shared

feat: improve sentry setup in Taxes App

---

.changeset/cold-trainers-help.md
apps/taxes/graphql/fragments/TaxBase.graphql
apps/taxes/src/modules/avatax/avatax-customer-code-resolver.test.ts
apps/taxes/src/modules/avatax/avatax-customer-code-resolver.ts
apps/taxes/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-mock-generator.ts
apps/taxes/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-payload-transformer.test.ts
apps/taxes/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-payload-transformer.ts
apps/taxes/src/modules/avatax/order-confirmed/avatax-order-confirmed-payload-transformer.ts
apps/taxes/src/modules/taxjar/calculate-taxes/taxjar-calculate-taxes-mock-generator.ts
cspell.json

**Featuring**:
- Extracted the logic of resolving the `customerCode` AvaTax field to a shared class. Now, instead of throwing an error, we return the recommended dummy value. It happens when there is no user id in checkout/order.
**Note**:
I updated the `TaxBase` fragment, but there is no need to perform migrations because we fall back to "0" (which is the default value in the AvaTax plugin anyway).

fix: cannot resolve customer code in Taxes App

---

README.md

The "Another official apps" heading is bigger than the "apps list" heading. IMO, it should be a sub-heading

Change heading level of "other official apps" in README

---

.changeset/dirty-crabs-count.md
apps/invoices/package.json
package.json
pnpm-lock.yaml

This PR resolves Dependabot security alert due to `crypto-js` critical vulrability: https://github.com/saleor/apps/security/dependabot/44
CVE-2023-46233

Apply override for vulnerable crypto-js versions

---

.github/workflows/prepare-release.yml

It makes force-pushes by changesets done by PAT user, instead github-actions token. Thanks to that, force push can trigger workflow (like build)

Update checkout workflow to fix build on release PR

---

.changeset/tidy-colts-dress.md
apps/search/src/lib/algolia/algoliaUtils.ts

No migrations because the field was already there.

feat: add SKU field in Search

---

.changeset/young-papayas-sin.md
apps/products-feed/graphql/fragments/GoogleFeedProductVariantFragment.graphql
apps/products-feed/src/modules/app-configuration/example-variant-data.ts
apps/products-feed/src/modules/google-feed/generate-google-xml-feed.test.ts
apps/products-feed/src/modules/google-feed/generate-google-xml-feed.ts
apps/products-feed/src/modules/google-feed/get-weight-attribute-value.test.ts
apps/products-feed/src/modules/google-feed/get-weight-attribute-value.ts
apps/products-feed/src/modules/google-feed/product-to-proxy.ts
apps/products-feed/src/modules/google-feed/types.ts

Added weight attribute to Google Feed.
The field is formatted according to the specyfication: https://support.google.com/merchants/answer/6324503?hl=en
Preview of the loaded data including the weight field:

Add weight attribute to the product feed

---

.changeset/five-cherries-juggle.md
apps/taxes/src/modules/avatax/avatax-client-tax-code.service.ts
apps/taxes/src/modules/avatax/avatax-client.ts
apps/taxes/src/modules/avatax/tax-code/avatax-tax-codes.router.ts
apps/taxes/src/modules/avatax/tax-code/avatax-tax-codes.service.ts
apps/taxes/src/modules/avatax/ui/avatax-tax-code-matcher-table.tsx
apps/taxes/src/modules/avatax/ui/tax-code-select.tsx
pnpm-lock.yaml

https://github.com/saleor/apps/assets/44495184/12cd18e2-3306-4a82-b6f8-b8c8bd6fca28
- Added the tax codes filtering in AvaTax
- Added a basic autocomplete component to be later replaced with [macaw-ui autocomplete](https://github.com/saleor/macaw-ui/issues/452)
- https://github.com/saleor/apps/issues/1130

feat: :sparkles: add autocomplete and tax codes filtering

---

.changeset/tiny-lobsters-complain.md
apps/slack/graphql/fragments/OwnWebhook.graphql
apps/slack/graphql/mutations/DisableWebhook.graphql
apps/slack/graphql/mutations/EnableWebhook.graphql
apps/slack/graphql/queries/FetchOwnWebhooks.graphql
apps/slack/src/lib/WebhookActivityToggler.service.ts
apps/slack/src/lib/is-valid-url.ts
apps/slack/src/pages/api/configuration.ts
apps/slack/src/pages/api/webhooks/order-created.ts

disable slack webhooks if app is not configured

---

apps/taxes/.env.example

This PR fixes `.env.example` for taxes app when it is developed with tunnel. Leaving those two env variables with empty values causes app to throw errors with `Invalid URL`. If you comment them out app works fine.

Update .env.example for taxes

---

README.md

I wanted to remove mention of monitoring app from README as there is no `apps/monitoring` folder anymore.

Remove monitoring app mention from README

---

.changeset/three-dryers-kneel.md
apps/emails-and-messages/graphql/fragments/OrderDetails.graphql
apps/emails-and-messages/src/modules/event-handlers/default-payloads.ts

I don't know, if this is sufficient, but the country area is missing currently - this PR is meant to add it. 
Open issue in the Saleor support slack

fix: adding country area

---

apps/emails-and-messages/src/modules/webhook-management/webhook-management-service.test.ts

Fixes test after #1177 
Reason of test to fail: in CI there is freshly regenerated graphql, locally its not enforced.

Fix test for e&m app

---

.changeset/soft-shoes-flash.md
apps/products-feed/src/modules/app-configuration/app-config.test.ts
apps/products-feed/src/modules/app-configuration/app-config.ts
apps/products-feed/src/modules/app-configuration/attribute-mapping-form.tsx
apps/products-feed/src/modules/google-feed/attribute-mapping.test.ts
apps/products-feed/src/modules/google-feed/attribute-mapping.ts
apps/products-feed/src/modules/google-feed/generate-google-xml-feed.ts
apps/products-feed/src/modules/google-feed/product-to-proxy.ts
apps/products-feed/src/modules/google-feed/types.ts
cspell.json

This PR makes it possible to link Saleor attribute to GTIN attribute in Google Feed app.

feat: add gtin attribute to the google feed app

---

.changeset/silly-trainers-carry.md
apps/taxes/graphql/fragments/TaxBase.graphql
apps/taxes/graphql/fragments/User.graphql
apps/taxes/graphql/subscriptions/OrderConfirmed.graphql
apps/taxes/src/modules/avatax/avatax-customer-code-resolver.test.ts
apps/taxes/src/modules/avatax/avatax-customer-code-resolver.ts
apps/taxes/src/modules/avatax/avatax-entity-type-matcher.ts
apps/taxes/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-mock-generator.ts
apps/taxes/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-payload-transformer.ts
apps/taxes/src/modules/avatax/order-confirmed/avatax-order-confirmed-payload-transformer.ts
apps/taxes/src/modules/taxjar/calculate-taxes/taxjar-calculate-taxes-mock-generator.ts

Taxes App synchronizes a group of fields from Saleor to an AvaTax transaction. Some of these fields are used to determine the tax value (e.g. the customer code).
The general approach is to use the Saleor field that matches the purpose of the AvaTax field the most. However, users sometimes want to override that value with their own. This usually comes into play when multiple other systems (where e.g. one system manages the customers) collaborate on the tax calculation. 
- Refactored the app to use `UserFragment` everywhere
- Added new logic to resolving AvaTax customer code. The app now tries to read it from metadata. If not found, it falls back to the user id. When no user id is found, it falls back to the dummy value (as AvaTax docs suggest).
This PR isn't breaking. If the metadata field …

Map customer code to a metadata field in the Taxes App

---

.github/workflows/changeset-checker.yml

Disable changeset check for release pr

---

apps/avatax/e2e/graphql/mutations/CheckoutAddVoucher.graphql

Add error fragment for voucher creation mutation in Avatax E2E tests

Add `CheckoutError` fragment to CheckoutAddVoucher mutation

---

apps/avatax/e2e/setup.ts
apps/avatax/vitest.workspace.ts

Update timeouts for PactumJS tests in Avatax, previously timeouts were raised for PactumJS but not vitest, which could have caused tests to be marked as failed due to timeout, even without doing any retries.
This PR also changes retry delay to be 50ms, instead of default 1000ms

Update timeouts for e2e tests in PactumJS

---

.github/workflows/e2e.yml

I added fail-fast strategy to e2e workflow. Currently if tests on 3.19 fails 3.18 job is canceled.

Add fail-fast strategy to e2e workflow

---

.changeset/violet-keys-help.md
apps/avatax/src/modules/avatax/order-confirmed/avatax-order-confirmed-payload-transformer.ts
apps/avatax/src/pages/api/webhooks/order-confirmed.ts

* Changes billing address to shipping address in `order-confirmed`
* Adds payload verification in `order-confirmed`

Use shipping address in `order-confirmed`

---

.changeset/little-ears-talk.md
apps/avatax/src/modules/app/webhook-response.ts
apps/avatax/src/pages/api/webhooks/order-cancelled.ts
apps/avatax/src/pages/api/webhooks/order-confirmed.ts

Cleanup `WebhookResponse.error` function - now it won't capture exception to Sentry. Instead you should use `Sentry.captureException` explicitly when there is unhandled exception. I also removed not needed `captureMessage` from `WebhookResponse.error`

Fix Sentry error logging for Avatax

---

.changeset/two-adults-repair.md
apps/avatax/bruno/package-lock.json
apps/avatax/src/lib/app-metadata-cache.ts
apps/avatax/src/modules/app/metadata-manager.test.ts
apps/avatax/src/modules/app/metadata-manager.ts
apps/avatax/src/modules/avatax/configuration/avatax-connection-repository.ts
apps/avatax/src/modules/avatax/configuration/avatax-connection.service.ts
apps/avatax/src/modules/avatax/tax-code/avatax-tax-code-matches.service.ts
apps/avatax/src/modules/channel-configuration/channel-configuration.service.ts
apps/avatax/src/pages/api/webhooks/checkout-calculate-taxes.ts
apps/avatax/src/pages/api/webhooks/order-calculate-taxes.ts
apps/avatax/src/pages/api/webhooks/order-cancelled.ts
apps/avatax/src/pages/api/webhooks/order-confirmed.ts

Added caching to App Metadata. Now, when webhook is called by Saleor, metadata from payload will be cached and consumed in MetadataManager. If cache doesn't exist, MetadataManager will fetch missing metadata. This change removes unnecessary graphql call that was timing out the handler.
Tested ORDER_CALCULATE_TAXES with this change and I couldn't get time longer than 2s

add metadata cache for webhooks

---

.github/workflows/e2e.yml
.github/workflows/run-e2e-dispatch.yml
.github/workflows/run-e2e-label.yml
apps/avatax/README.md

We want e2e workflow to run:
1. When label is added
2. When dispatched manually (or via other workflow)
To accomplish this I splitted workflow in two.

Split e2e workflow into two: one for label second for dispatch

---

.changeset/honest-wombats-jump.md
apps/avatax/src/pages/api/manifest.ts
packages/logger/src/logger-sentry-transport.ts

Fixes sentry breadcrumbs timestamp
https://linear.app/saleor/issue/SHOPX-471/sentry-breadcrumbs-are-broken

fix Sentry breadcrumb dates

---

apps/avatax/.graphqlrc.ts
apps/avatax/src/mocks.ts
apps/avatax/src/modules/saleor/mock-order-factory.ts
apps/avatax/src/modules/saleor/order.ts

Before:
After
when researching found that we should update graphql-codegen
1. https://the-guild.dev/graphql/codegen/plugins/typescript/typed-document-node this should not be used directly
2. https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-document-nodes this can be configured to use JSON instead `gql` which may be smaller in bundle size (gql has a lot of whitespace) → need to be checked
3. using client-preset is recommended so we should migrate

use type instead enums in codegen types

---

.changeset/rare-insects-remain.md
apps/avatax/src/lib/app-configuration-logger.test.ts
apps/avatax/src/lib/app-configuration-logger.ts
apps/avatax/src/modules/taxes/get-active-connection-service.ts

With this log, datadog etc can consume specific values, like errors in config, or if some options are set, for debugging

Add logger that will log specific app configuration log

---

.changeset/hungry-beers-sip.md
.changeset/lemon-drinks-cross.md
apps/search/src/domain/WebhookActivityToggler.service.ts
apps/search/src/lib/algolia/algolia-error-parser.test.ts
apps/search/src/lib/algolia/algolia-error-parser.ts
apps/search/src/lib/algolia/algoliaSearchProvider.ts
apps/search/src/modules/trpc/protected-client-procedure.ts
apps/search/src/pages/api/webhooks/saleor/product_created.ts
apps/search/src/pages/api/webhooks/saleor/product_deleted.ts
apps/search/src/pages/api/webhooks/saleor/product_updated.ts
apps/search/src/pages/api/webhooks/saleor/product_variant_back_in_stock.ts
apps/search/src/pages/api/webhooks/saleor/product_variant_created.ts
apps/search/src/pages/api/webhooks/saleor/product_variant_deleted.ts
apps/search/src/pages/api/webhooks/saleor/product_variant_out_of_stock.ts
apps/search/src/pages/api/webhooks/saleor/product_variant_updated.ts

Fixed problem when webhooks were disabled if _any_ error from Algolia was received. Now only 401 and 403 errors (invalid auth/credentials) will cause webhooks disabling, until app is configured again.
Fixed logger execution to properly attach attributes

Check algolia errors and disable webhooks only if auth error occured

---

apps/smtp/package.json
apps/smtp/scripts/deploy.ts
apps/smtp/src/release-utils.ts
apps/smtp/turbo.json
pnpm-lock.yaml

Fix SMTP app deploy

---

.changeset/sour-frogs-cheat.md
apps/avatax/src/lib/error-utils.test.ts
apps/avatax/src/lib/error-utils.ts

Don't send handled error for `checkoutCalculateTaxes` event into Sentry. It will be logged instead.

Don't send handled error for `checkoutCalculateTaxes` event into Sentry

---

apps/avatax/next.config.js

We updated sentry to 8.0.0 and it is bundling OTEL instrumentation which is causing a spam of errors in dev console. This PR mutes them.

Mute OTEL warnings

---

apps/smtp/README.md
apps/smtp/src/modules/event-handlers/send-event-messages.use-case.test.ts
apps/smtp/src/modules/event-handlers/send-event-messages.use-case.ts
apps/smtp/src/modules/event-handlers/use-case/send-event-messages.use-case.factory.ts
apps/smtp/src/modules/event-handlers/use-case/send-event-messages.use-case.test.ts
apps/smtp/src/modules/event-handlers/use-case/send-event-messages.use-case.ts
apps/smtp/src/modules/smtp/configuration/smtp-configuration.router.ts
apps/smtp/src/modules/smtp/configuration/smtp-configuration.service.ts
apps/smtp/src/modules/smtp/configuration/smtp-metadata-manager.ts
apps/smtp/src/modules/smtp/services/smtp-email-sender.ts
apps/smtp/src/pages/api/webhooks/gift-card-sent.ts
apps/smtp/src/pages/api/webhooks/invoice-sent.ts
apps/smtp/src/pages/api/webhooks/notify.ts
apps/smtp/src/pages/api/webhooks/order-cancelled.ts
apps/smtp/src/pages/api/webhooks/order-confirmed.ts
apps/smtp/src/pages/api/webhooks/order-created.ts
apps/smtp/src/pages/api/webhooks/order-fulfilled.ts
apps/smtp/src/pages/api/webhooks/order-fully-paid.ts
apps/smtp/src/pages/api/webhooks/order-refunded.ts

SMTP App: Tests for main business useCase

---

.changeset/friendly-apes-compare.md
apps/products-feed/src/modules/google-feed/fetch-product-data.ts

The cursor for the first page was not used. The code directly always took the second page.

Fix skipping first page cursor

---

.changeset/chilled-trains-move.md
apps/search/next.config.js

Vercel metrics shows about 5s lower cold start on webhooks

search - optimize packages

---

.changeset/early-moose-fix.md
apps/smtp/src/pages/api/register.ts
apps/smtp/src/pages/api/webhooks/gift-card-sent.ts
apps/smtp/src/pages/api/webhooks/invoice-sent.ts
apps/smtp/src/pages/api/webhooks/notify.ts
apps/smtp/src/pages/api/webhooks/order-cancelled.ts
apps/smtp/src/pages/api/webhooks/order-confirmed.ts
apps/smtp/src/pages/api/webhooks/order-created.ts
apps/smtp/src/pages/api/webhooks/order-fulfilled.ts
apps/smtp/src/pages/api/webhooks/order-fully-paid.ts
apps/smtp/src/pages/api/webhooks/order-refunded.ts

Fix SMTP timeout by trycatching usecase

---

.github/workflows/prepare-release.yml

Pins pnpm to 4.0.0 as previously used version has deprecated Node

Pin pnpm version for release workflow

---

.github/workflows/e2e.yml

I want to extend workflow matrix to run e2e for the AvaTax App on the 3.20 Saleor version
I tested the workflow from the branch and looks like all pieces were setup correctly and we can start running CI on 3.20 version.

Add env 320 to e2e matrix

---

knip.json
package.json
pnpm-lock.yaml

Install knip package. It can be now locally executed (`npm run knip`) to review unused, dead code
It has basic cofnig: works out of the box with monorepo and next.js. It also excludes generated graphql.
Other false-positives must be configured separately.
Eventually we can include this to our CICD

install knip

---

.changeset/selfish-scissors-shop.md
apps/smtp/src/modules/smtp/services/mjml-compiler.ts

Context:
- Some time ago [we have changed](https://github.com/saleor/apps/pull/1450) "import" to "require" due to silent timeouts
- It did solve the problem, but turns out not completelly, timeouts still happen, the execution time is lower, however still sometimes exceeds the limit
- When `bundlePagesExternals` is enabled, and mjml is mentioned in `serverComponentsExternalPackages`, the regular "import" seems working fine, reducing webhook processing calls to ~2s

Replace "require" with import

---

packages/logger/src/logger-console-transport.ts
packages/logger/src/logger.test.ts

This stringfies attributes passed to logger. 
| Before | After |
| ------- | ------- |
| `log { array: [Object object] }` | `log {array: [{obj: key}]}` |

Stringify attributes passed to console transport

---

apps/avatax/e2e/setup.ts

Try to print more verbose logs from Pactum, so failed tests will be easier to debug (hopefully)

Set Avatax e2e tests to print DEBUG level logs

---

.changeset/witty-coins-notice.md
package.json
pnpm-lock.yaml

https://linear.app/saleor/issue/SHOPX-989/fix-incorrect-app-sdk-span

update app sdk to 0.50.2

---

.github/workflows/e2e.yml
apps/avatax/e2e/data/maps/product.json
apps/avatax/e2e/data/maps/voucher.json
apps/avatax/e2e/data/templates/addVoucher.json
apps/avatax/e2e/data/templates/checkout.json
apps/avatax/e2e/data/templates/updateCheckoutLines.json
apps/avatax/e2e/graphql/fragments/CheckoutDetails.graphql
apps/avatax/e2e/graphql/mutations/CheckoutLinesUpdate.graphql
apps/avatax/e2e/graphql/mutations/CreateCheckout.graphql
apps/avatax/e2e/graphql/mutations/CreateCheckoutNoAddress.graphql
apps/avatax/e2e/graphql/mutations/OrderAddDiscount.graphql
apps/avatax/e2e/tests/checkout_address_change_with_product_tax.spec.ts
apps/avatax/e2e/tests/checkout_order_promotion_subtotal_reward.spec.ts
apps/avatax/e2e/tests/checkout_with_product_tax.spec.ts
apps/avatax/e2e/tests/checkout_with_voucher_free_shipping.spec.ts
apps/avatax/e2e/tests/draft_order_with_manual_total_discount.spec.ts
apps/avatax/e2e/tests/order_with_product_tax.spec.ts

Add 3 more tests to cover 
- checkout with a free shipping voucher - discount only on shipping
- checkout with order promotion with subtotal reward - discount only on subtotal
- draft order with manual discount - discount on subtotal and shipping
https://linear.app/saleor/issue/SHOPX-1341/add-e2e-test-in-avatax

Add more e2e tests for discounts applied to checkout or draft order

---

apps/avatax/scripts/run-webhooks-migration.ts

Despite being faster, some of the migration calls were rejected due to underlying Saleor mechanisms
This PR restores "slow" migration but it will be rate-limited again, hopefully making it reliable
In the future we can control this via env:
- in production make it slow but reliable
- in dev/staging make it fast, but accept the failure

Restore sequential migration script

---

.changeset/shiny-wombats-melt.md
apps/avatax/src/modules/avatax/order-cancelled/avatax-order-cancelled-adapter.test.ts
apps/avatax/src/modules/avatax/order-cancelled/avatax-order-cancelled-adapter.ts
apps/avatax/src/pages/api/webhooks/order-cancelled.ts

handle document not found error in avatax during cancel

---

.changeset/early-kangaroos-boil.md
apps/avatax/src/modules/avatax/avatax-errors-parser.test.ts
apps/avatax/src/modules/avatax/avatax-errors-parser.ts
apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-adapter.ts
apps/avatax/src/modules/avatax/configuration/avatax-address-validation.service.ts
apps/avatax/src/modules/avatax/order-cancelled/avatax-order-cancelled-adapter.ts

Improved error parser class constructor: now `parse` method will have optional parameter of error capture instead of constructor. This change will not have effect on clients.

Improve error parser constructor

---

.changeset/silent-melons-yawn.md
apps/avatax/saleor-app.ts
apps/avatax/src/pages/api/manifest.ts
apps/avatax/src/pages/api/register.ts

Remove version checking on AvaTax register endpoint

---

apps/avatax/src/modules/avatax/avatax-webhook.service.ts
apps/avatax/src/modules/avatax/order-confirmed/avatax-order-confirmed-adapter.ts
apps/avatax/src/modules/avatax/order-confirmed/avatax-order-confirmed-payload-transformer.test.ts
apps/avatax/src/modules/avatax/order-confirmed/avatax-order-confirmed-payload-transformer.ts
apps/avatax/src/modules/avatax/order-confirmed/avatax-order-confirmed-payload.service.ts
apps/avatax/src/modules/saleor/index.ts
apps/avatax/src/modules/saleor/order-confirmed/event.test.ts
apps/avatax/src/modules/saleor/order-confirmed/event.ts
apps/avatax/src/modules/saleor/order-confirmed/mocks.ts
apps/avatax/src/modules/saleor/types.ts
apps/avatax/src/pages/api/webhooks/order-confirmed.ts

refactor order confirmed event

---

apps/avatax/e2e/data/maps/product.json
apps/avatax/e2e/data/templates/order.json
apps/avatax/e2e/graphql/fragments/OrderDetails.graphql
apps/avatax/e2e/graphql/fragments/OrderDiscounts.graphql
apps/avatax/e2e/graphql/mutations/CreateOrderLines.graphql
apps/avatax/e2e/graphql/mutations/DraftOrderUpdateVoucher.graphql
apps/avatax/e2e/graphql/mutations/OrderAddDiscount.graphql
apps/avatax/e2e/graphql/mutations/OrderLineUpdate.graphql
apps/avatax/e2e/tests/checkout_address_change.spec.ts
apps/avatax/e2e/tests/checkout_basic_product_with_tax_code.spec.ts
apps/avatax/e2e/tests/checkout_basic_product_without_tax_code.spec.ts
apps/avatax/e2e/tests/checkout_order_promotion_subtotal_reward.spec.ts
apps/avatax/e2e/tests/checkout_with_entire_voucher.spec.ts
apps/avatax/e2e/tests/checkout_with_voucher_free_shipping.spec.ts
apps/avatax/e2e/tests/draft_order_basic.spec.ts
apps/avatax/e2e/tests/draft_order_catalog_promotion.spec.ts
apps/avatax/e2e/tests/draft_order_with_entire_voucher.spec.ts
apps/avatax/e2e/tests/draft_order_with_manual_total_discount.spec.ts
apps/avatax/e2e/tests/draft_order_with_order_promotion_subtotal.spec.ts
apps/avatax/e2e/utils/moneyUtils.ts

Add new e2e for discounts on draft orders:
- draft order with products on catalog discount [AVATAX_24](https://saleor.testmo.net/repositories/6?group_id=4846&sort_column=repository_cases:custom_automated&sort_direction=asc&case_id=18388)
- draft order with voucher [AVATAX_28](https://saleor.testmo.net/repositories/6?group_id=4846&sort_column=repository_cases:custom_automated&sort_direction=asc&case_id=18392)
- draft order with order promotion [AVATAX_32](https://saleor.testmo.net/repositories/6?group_id=4846&sort_column=repository_cases:custom_automated&sort_direction=asc&case_id=24175)
Remove the check for metadata since it's flaky

[E2E] Add tests for discounts on draft orders

---

apps/avatax/e2e/data/maps/channel.json
apps/avatax/e2e/data/maps/product.json
apps/avatax/e2e/data/templates/order.json
apps/avatax/e2e/data/templates/updateDeliveryMethod.json
apps/avatax/e2e/graphql/mutations/CreateDraftOrder.graphql
apps/avatax/e2e/graphql/mutations/UpdateMetadata.graphql
apps/avatax/e2e/tests/checkout_with_click_and_collect.spec.ts
apps/avatax/e2e/tests/checkout_with_customer_metadata.spec.ts
apps/avatax/e2e/tests/checkout_with_digital_products.spec.ts
apps/avatax/e2e/tests/draft_order_with_entity_code.spec.ts

Add new e2e:
- complete checkout with metadata avataxCustomerCode [AVATAX_15](https://saleor.testmo.net/repositories/6?group_id=139&case_id=16247)
- complete draft order with metadata avataxEntityCode [AVATAX_36](https://saleor.testmo.net/repositories/6?group_id=4846&case_id=24363)
- complete checkout with click and collect (warehouse) - shipping address changed to warehouse address [AVATAX_19](https://saleor.testmo.net/repositories/6?group_id=139&case_id=18383)
- complete checkout with digital-only products - only billing address needed [AVATAX_8](https://saleor.testmo.net/repositories/6?group_id=139&case_id=16239)

[E2E] Add tests for metadata, digital checkout, and checkout with click and collect

---

apps/avatax/e2e/graphql/mutations/DraftOrderLineDelete.graphql
apps/avatax/e2e/tests/draft_order_changing_lines.spec.ts

Add new e2e check tax calculation after changing lines on draft order add/update/remove [AVATAX_26](https://saleor.testmo.net/repositories/6?group_id=4846&pagination_current=2&case_id=18390)

[E2E] Add test for update lines on draft order

---

.changeset/few-apes-fetch.md
apps/avatax/src/pages/api/webhooks/checkout-calculate-taxes.ts

https://docs.aws.amazon.com/lambda/latest/operatorguide/static-initialization.html
Based on that I want to verify hypothesis that lambda will start faster

Avatax: Experimentally create dependencies inside the handler

---

.changeset/sour-buttons-allow.md
apps/avatax/.env.example
apps/avatax/src/pages/api/manifest.ts
apps/avatax/turbo.json

avatax allow to inject manifest id

---

.changeset/weak-crabs-melt.md
packages/logger/src/logger-vercel-transport.ts

Added missing OTEL attributes to `loggerVercelTransport`. They will be visible under `otel` key in log collection service.
Attributes:
* `span_id`
* `trace_id`
* `timestamp`

Fix vercel transport OTEL attrs

---

.changeset/healthy-pianos-marry.md
.changeset/violet-candles-hide.md
apps/avatax/scripts/migration-logger.ts
apps/avatax/scripts/run-webhooks-migration.ts
apps/avatax/src/lib/app-configuration-logger.ts
apps/avatax/src/lib/error-utils.ts
apps/avatax/src/logger.ts
apps/cms-v2/src/logger.ts
apps/cms-v2/src/modules/providers/contentful/contentful-client.ts
apps/cms-v2/src/modules/providers/payloadcms/payloadcms-bulk-sync-processor.ts
apps/cms-v2/src/modules/trpc/protected-client-procedure.ts
apps/klaviyo/src/logger.ts
apps/products-feed/src/logger.ts
apps/search/src/lib/logger.ts
apps/smtp/src/logger.ts
packages/logger/index.ts
packages/logger/src/logger.test.ts
packages/logger/src/root-logger.test.ts
packages/logger/src/root-logger.ts

Renamed exported `logger` to `rootLogger` so we avoid collision of names when using `logger` in monorepo. Also `createLogger` function has been removed in favour of app defining it in their codebase.

Refactor logger

---

.changeset/dull-chairs-breathe.md
.cspell.json
apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-response-lines-transformer.ts
apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-response-shipping-transformer.ts

Added warning logs when Avalara returns `isFee` in product or shipping line details.

Add logs when we found `isFee` from Avalara response

---

.changeset/green-jokes-burn.md
apps/avatax/scripts/run-webhooks-migration.ts

Run webhook migrations in parallel instead of sequentially.

Run webhook migrations in parallel for AvaTax

---

apps/avatax/src/env.ts

Fix PORT env vars for AvaTax

---

.changeset/rare-crews-end.md
packages/logger/package.json
packages/logger/src/errors.ts
packages/logger/src/logger-vercel-runtime-transport.ts
pnpm-lock.yaml

If Vercel runtime transport log is exceeding Vercel log limit (4kb) error to Sentry will be logged as it won't be visible in log drain.

Add support for Vercel log limit

---

.changeset/eighty-brooms-help.md
packages/logger/src/logger-vercel-runtime-transport.ts

Fix Vercel runtime transport logs attribute order - attributes from logs context will be first so log attributes can override them.

Fix order of logs attributes

---

.changeset/little-zoos-tan.md
apps/products-feed/src/pages/api/feed/[url]/[channel]/google.xml.ts

Add more information about size of the generated payload

---

apps/avatax/src/modules/avatax/address-factory.test.ts
packages/eslint-config-saleor/index.js
packages/eslint-config-saleor/package.json
pnpm-lock.yaml

Install Vitest eslint plugin

---

.github/workflows/e2e.yml
.github/workflows/main.yml
.github/workflows/prepare-release.yml
CODEOWNERS

* This PR adds setup-node action so proper version of Node (22) instead of default (20 for GHA) is used
* It also adds cache via https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time

Add setup node to GHA workflow

---

apps/segment/README.md

Add README to Segment app

---

.changeset/rotten-seals-suffer.md
apps/avatax/package.json
apps/avatax/src/pages/api/register.ts
apps/cms-v2/package.json
apps/cms-v2/src/pages/api/register.ts
apps/klaviyo/package.json
apps/klaviyo/src/pages/api/register.ts
apps/products-feed/package.json
apps/products-feed/src/pages/api/register.ts
apps/search/package.json
apps/search/src/pages/api/register.ts
apps/smtp/package.json
apps/smtp/src/pages/api/register.ts
pnpm-lock.yaml

Escape ALLOWED_DOMAIN_PATTERN regex. It ensures that regex constructed from env variable is sanitized and can't be used to Denial of Service attack.

Fix code scan issue with `ALLOWED_DOMAIN_PATTERN` regex

---

.changeset/honest-sheep-happen.md
apps/avatax/next.config.js
apps/avatax/package.json
apps/avatax/src/modules/client-logs/client-logs.router.ts
apps/avatax/src/modules/client-logs/logs-repository.test.ts
apps/avatax/src/modules/client-logs/logs-repository.ts
apps/avatax/src/modules/client-logs/ui/format-date.ts
apps/avatax/src/modules/client-logs/ui/logs-browser.tsx
apps/avatax/src/modules/client-logs/ui/use-client-logs-pagination.test.tsx
apps/avatax/src/modules/client-logs/ui/use-client-logs-pagination.tsx
pnpm-lock.yaml

* Implemented client logs cache. Right now app will cache request for 1 day and revalidate the cache every 60 seconds.
* Added forward / backward pagination to client logs. After this change end user can browse logs that exceeds current pagination limit (first 100).

Cache TRPC query for logs & implement logs pagination

---

.github/workflows/main.yml
apps/avatax/package.json
apps/cms-v2/package.json
apps/products-feed/package.json
apps/search/package.json
apps/segment/package.json
apps/smtp/package.json
codecov.yml
package.json
packages/logger/package.json
packages/shared/package.json
packages/webhook-utils/package.json
pnpm-lock.yaml

Setup codecov

---

.changeset/silly-months-clean.md
apps/segment/vercel.json

* Set Vercel function memory allocation to 1024 and max duration to 15 seconds.

Setup Segment API func memory & max duration

---

.changeset/gold-dryers-talk.md
apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-response-lines-transformer.test.ts
apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-response-lines-transformer.ts

reset tax rate to 0 if taxable amount is zero

---

apps/avatax/src/pages/api/webhooks/checkout-calculate-taxes.ts

Add debug log for AvaTax calc taxes

---

.github/workflows/e2e.yml
apps/avatax/e2e/tests/checkout_with_customer_metadata.spec.ts
apps/avatax/src/pages/api/webhooks/checkout-calculate-taxes.ts

This PR fixes e2e for AvaTax to be in sync what we will recommend in docs:
* Update checkout metadata as early as possible in checkout flow as from 3.21 forcing recalculating of checkout by updating delivery method to the same that is on checkout won't trigger webhook to tax app

Fix e2e for AvaTax

---

.changeset/neat-cherries-check.md
packages/otel/src/otel-urql-exchange-factory.ts
packages/otel/tsconfig.json

Remove deprecated `SemanticAttributes.HTTP_URL` from `otelUrqlExchangeFactory` and use `ATTR_URL_FULL` instead

Fix deprecated span attr for `urqlExchange`

---

.changeset/little-bottles-battle.md
.changeset/lovely-zoos-grab.md
apps/avatax/src/instrumentations/otel-node.ts
apps/segment/src/instrumentations/otel-node.ts
package.json
packages/otel/package.json
packages/otel/src/aws-instrumentation-factory.ts
packages/otel/src/http-instrumentation-factory.ts
packages/otel/src/otel-urql-exchange-factory.ts
pnpm-lock.yaml

* Properly disable HTTP instrumentation for Sentry requests. Added `AwsInstrumentation` factory that can be used to auto instrument DynamoDB calls.

Add AWS instrumentation for DynamoDB and disable HTTP instrumentation for Sentry requests

---

.changeset/small-moles-tell.md
apps/avatax/src/modules/avatax/avatax-client-tax-code.service.test.ts
apps/avatax/src/modules/avatax/avatax-client-tax-code.service.ts
apps/avatax/src/modules/avatax/avatax-client.ts
apps/avatax/src/modules/avatax/avatax-entity-type-matcher.test.ts
apps/avatax/src/modules/avatax/avatax-entity-type-matcher.ts
apps/avatax/src/modules/avatax/avatax-errors-parser.ts
apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-adapter.ts
apps/avatax/src/modules/avatax/calculate-taxes/avatax-calculate-taxes-payload-transformer.test.ts
apps/avatax/src/modules/avatax/configuration/avatax-address-validation.service.ts
apps/avatax/src/modules/avatax/configuration/avatax-auth-validation.service.ts
apps/avatax/src/modules/avatax/order-cancelled/avatax-order-cancelled-adapter.test.ts
apps/avatax/src/modules/avatax/order-cancelled/avatax-order-cancelled-adapter.ts
apps/avatax/src/modules/avatax/order-confirmed/avatax-order-confirmed-adapter.ts
apps/avatax/src/modules/avatax/tax-code/avatax-tax-codes.service.ts
apps/avatax/src/modules/calculate-taxes/use-case/calculate-taxes.use-case.test.ts
apps/avatax/src/modules/taxes/tax-error.ts

* Refactored AvaTax client to use `nevethrow` - thanks to that it will be easier to wrap AvaTax methods with custom spans and set span statuses based on response.

Refactor AvaTax client to use nevethrow

---

turbo.json

Solves warnings during Vercel deployments:
```
Warning - the following environment variables are set on your Vercel project, but missing from "turbo.json". These variables WILL NOT be available to your application and may cause your build to fail. Learn more at https://turbo.build/repo/docs/platform-environment-variables
[warn] saleor-app-avatax#deploy
[warn]   - OTEL_EXPORTER_OTLP_ENDPOINT 
[warn]   - OTEL_TRACES_SAMPLER_ARG 
[warn]   - OTEL_TRACES_SAMPLER 
[warn]   - ENABLE_EXPERIMENTAL_COREPACK 
[warn]   - OTEL_LOG_LEVEL 
[warn]   - REPOSITORY_URL 
```

Add missing env vars to turbo configuration

---

turbo.json

* Brings back `lint:fix` task - currently it isn't possible to run it from root of monorepo
* Brings back `test` task but disables cache for it - by default test tasks are running vitest in watch mode so there is no reason to cache that

Bring back lint:fix & test tasks

---

.github/workflows/help-wanted-issues-to-discord.yml

Add GitHub Action to notify Discord on "Help Wanted" issues the same way we do in saleor/saleor

Add GitHub Action to notify Discord on "Help Wanted" issues

---

.devcontainer/avatax/Dockerfile
.devcontainer/avatax/devcontainer.json
.devcontainer/cms/Dockerfile
.devcontainer/cms/devcontainer.json
.devcontainer/klaviyo/Dockerfile
.devcontainer/klaviyo/devcontainer.json
.devcontainer/products-feed/Dockerfile
.devcontainer/products-feed/devcontainer.json
.devcontainer/search/Dockerfile
.devcontainer/search/devcontainer.json
.devcontainer/segment/Dockerfile
.devcontainer/segment/devcontainer.json
.devcontainer/smtp/Dockerfile
.devcontainer/smtp/devcontainer.json
.devcontainer/stripe/Dockerfile
.devcontainer/stripe/devcontainer.json
apps/avatax/README.md
apps/cms/README.md
apps/klaviyo/README.md
apps/products-feed/README.md
apps/search/README.md
apps/segment/README.md
apps/smtp/README.md
apps/stripe/README.md

* Fixed when we install dependencies - after this change deps will be installed in devcontainer `postCreateCommand` instead in dockerfile. 
This is because in dockerfile there isn't volume with codebase connected yet - I will be connected in docker-compose. 
* Removed fix for corepack - it actually was causing docker builds to fail
* Removed `filter` from `pnpm install` - each app will have to have full deps in dev mode anyway

Fix devcontainer setup

---

apps/stripe/package.json
apps/stripe/src/app/api/manifest/route.integration.test.ts
apps/stripe/src/app/api/saleor/payment-gateway-initialize-session/webhook-definition.ts
apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case.test.ts
apps/stripe/src/app/api/saleor/transaction-initialize-session/use-case.ts
apps/stripe/src/modules/saleor/saleor-money.test.ts
apps/stripe/src/modules/saleor/saleor-money.ts
apps/stripe/src/modules/stripe/stripe-money.test.ts
apps/stripe/src/modules/stripe/stripe-money.ts
pnpm-lock.yaml

- Introduced `SaleorMoney` and `StripeMoney` classes for currency conversion and validation.
- Updated `TransactionInitializeSessionUseCase` to utilize new money classes.
- Enhanced integration tests to cover currency validation scenarios.
- Added dependencies for currency handling in `package.json`.

Add currency handling and validation for Stripe integration

---

apps/klaviyo/src/pages/api/webhooks/customer-created.ts
apps/klaviyo/src/pages/api/webhooks/fulfillment-created.ts
apps/klaviyo/src/pages/api/webhooks/order-created.ts
apps/klaviyo/src/pages/api/webhooks/order-fully-paid.ts
apps/stripe/package.json
apps/stripe/src/app/api/saleor/payment-gateway-initialize-session/route.ts
apps/stripe/src/app/api/saleor/transaction-initialize-session/route.ts
packages/eslint-config/index.js

Based on https://typescript-eslint.io/rules/no-unused-vars/#what-benefits-does-this-rule-have-over-typescript so unused vars can be renamed to `_VARNAME`

Add eslint rule for unused vars

---

apps/stripe/src/modules/saleor/transaction-event-reporter.test.ts
apps/stripe/src/modules/saleor/transaction-event-reporter.ts

Instead of passing server error from urql as a cause I changed and pass graphql error from mutation as cause

Improve Stripe webhook error handling with error cause

---

.changeset/angry-dots-jog.md
apps/cms/src/modules/bulk-sync/bulk-sync-view.tsx
apps/cms/src/modules/providers/strapi/strapi-bulk-sync-processor.ts
apps/cms/src/modules/providers/strapi/strapi-client.ts
apps/cms/turbo.json

Added bulk processing of uploading products to Strapi CMS. After this change you can use `STRAPI_BATCH_SIZE` to control number to request send in the same batch to Strapi API with `STRAPI_MILIS_DELAY_BETWEEN_BATCHES` controlling how frequent those batches are send to Strapi API.
This is in preview - after we confirm that batching works for clients we can add global setting for other providers.

Add bulk processing for Strapi CMS provider

---

apps/stripe/src/__tests__/integration/webhooks/fixtures/transaction-initialize-session-fixture.ts
apps/stripe/src/__tests__/integration/webhooks/transaction-cancelation-requested.test.ts
apps/stripe/src/__tests__/integration/webhooks/transaction-charge-requested.test.ts
apps/stripe/src/__tests__/integration/webhooks/transaction-process-session.test.ts
apps/stripe/src/__tests__/integration/webhooks/transaction-refund-requested.test.ts
apps/stripe/src/__tests__/mocks/constants.ts
apps/stripe/src/__tests__/mocks/mocked-recorded-transaction.ts
apps/stripe/src/__tests__/mocks/saleor-events/transaction-cancelation-request-event.ts
apps/stripe/src/__tests__/mocks/saleor-events/transaction-charge-requested-event.ts
apps/stripe/src/__tests__/mocks/saleor-events/transaction-initialize-session-event.ts
apps/stripe/src/__tests__/mocks/saleor-events/transaction-process-session-event.ts
apps/stripe/src/__tests__/mocks/saleor-events/transaction-refund-request-event.ts
apps/stripe/src/app/api/webhooks/saleor/transaction-cancelation-requested/use-case.test.ts
apps/stripe/src/app/api/webhooks/saleor/transaction-charge-requested/use-case.test.ts
apps/stripe/src/app/api/webhooks/saleor/transaction-initialize-session/use-case.test.ts
apps/stripe/src/app/api/webhooks/saleor/transaction-process-session/use-case.test.ts
apps/stripe/src/app/api/webhooks/saleor/transaction-refund-requested/use-case.test.ts
apps/stripe/src/app/api/webhooks/stripe/transaction-event-report-variables-resolver.test.ts
apps/stripe/src/app/api/webhooks/stripe/use-case-error.test.ts
apps/stripe/src/app/api/webhooks/stripe/use-case-success.test.ts
apps/stripe/src/modules/stripe/stripe-payment-intents-api.test.ts
apps/stripe/src/modules/transactions-recording/repositories/dynamodb/dynamodb-transaction-recorder-repo.test.ts
apps/stripe/src/modules/transactions-recording/repositories/dynamodb/recorded-transaction-db-model.test.ts

* Removed deprecated `mockedSaleorTransactionId` and use branded one (with rename)
* Moved Saleor events mocks into own folder

Refactor Stripe tests mocks

---

.changeset/fix-stripe-metadata-missing.md
.changeset/giant-parents-collect.md
apps/stripe/src/modules/stripe/stripe-payment-intents-api.test.ts
apps/stripe/src/modules/stripe/stripe-payment-intents-api.ts

Stripe webhooks fail with \"Object created outside of Saleor is not processable\" when processing PaymentIntents created via `transactionInitialize`.
Add missing metadata (saleor_transaction_id, saleor_source_id, saleor_source_type) to Stripe API call in `createPaymentIntent`.
The metadata was being prepared but not passed to Stripe's API. This issue surfaced after the July 24 security update that enforces metadata validation.
- Pass metadata to `paymentIntents.create()` API call
- Add test coverage for metadata handling

Fix Stripe PaymentIntent metadata not being passed to API

---

.changeset/wet-onions-jog.md
apps/avatax/src/modules/avatax/ui/avatax-configuration-address-fragment.tsx
apps/avatax/src/modules/avatax/ui/avatax-configuration-credentials-fragment.tsx
apps/avatax/src/modules/avatax/ui/avatax-tax-code-matcher-table.tsx
apps/avatax/src/modules/avatax/ui/edit-avatax-configuration.tsx
apps/avatax/src/modules/channel-configuration/ui/channel-list.tsx
apps/avatax/src/modules/channel-configuration/ui/channel-table.tsx
apps/avatax/src/modules/provider-connections/ui/providers-list.tsx
apps/avatax/src/modules/provider-connections/ui/providers-section.tsx
apps/avatax/src/modules/ui/matcher-section.tsx
apps/avatax/src/modules/ui/providers-table.tsx
apps/avatax/src/pages/configuration.tsx
apps/avatax/src/pages/providers/avatax/matcher.tsx

Update AvaTax UI. This includes: removing providers mentions where possible, changing form labels of AvaTax configuration, adding breadcrumbs to tax code matcher view.
Configurations page:
Single configuration page:
Tax code matcher page:

Update AvaTax UI

---

.changeset/chilly-oranges-dance.md
apps/avatax/src/modules/avatax/avatax-document-code-resolver.test.ts
apps/avatax/src/modules/avatax/avatax-document-code-resolver.ts
apps/avatax/src/modules/avatax/order-confirmed/avatax-order-confirmed-payload-transformer.ts
apps/avatax/src/modules/saleor/order-confirmed/event.ts

Send Saleor order number instead of order id as AvaTax document code. Previously app was using first 20 characters of order id. This was causing a problem on AvaTax side as there weren't any way of connecting Saleor order (as order id was truncated to first 20 chars). After this change app will send order number (e.g 2137) instead. Thanks to that you will see it in AvaTax dashboard and you will be able to use this number for searching for order in Saleor.
This is how is going to look in AvaTax dashboard:

Pass order number as document code

---

.changeset/violet-pets-camp.md
apps/smtp/src/lib/notify-event-types.ts
apps/smtp/src/modules/event-handlers/default-payloads.ts

Fixed default payload for the following emails:
- accountChangeEmailRequest - changed invalid `reset_url` field to `redirect_url`
- accountChangeEmailConfirm - removed two fields that doesn't exist in the payload for this event:`token` and `reset_url`

Fix example payload for email change request and confirmation emails
